### ISSUE TITLE
Some images failing to load due to different exceptions

### ISSUE THREAD

**Issue by devedse** [SixLabors/ImageSharp#1014]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

#### Image 01.png
![01](https://user-images.githubusercontent.com/2350015/65526107-cf1fdd00-def0-11e9-9af1-2c0e89cb5705.png)

```
01.png
Exception happened when optimizing or comparing the image:
SixLabors.ImageSharp.ImageFormatException: Unknown filter type.
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.DecodePixelData[TPixel](Stream compressedStream, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at DeveImageOptimizer.Helpers.ImageComparer.LoadImageHelper(String imagePath, List`1 tempFiles, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 34
   at DeveImageOptimizer.Helpers.ImageComparer.AreImagesEqual(String image1Path, String image2Path, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 56
   at DeveImageOptimizer.Helpers.ImageComparer.<>c__DisplayClass0_0.<AreImagesEqualAsync>b__0() in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 20
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(String fileToOptimize, String originDirectory) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\FileProcessing\FileOptimizerProcessor.cs:line 100
```

#### Image 03.png

![03](https://user-images.githubusercontent.com/2350015/65526374-4ce3e880-def1-11e9-989f-be1d041de598.png)

```
03.png
Exception happened when optimizing or comparing the image:
System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.DecodePixelData[TPixel](Stream compressedStream, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at DeveImageOptimizer.Helpers.ImageComparer.LoadImageHelper(String imagePath, List`1 tempFiles, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 34
   at DeveImageOptimizer.Helpers.ImageComparer.AreImagesEqual(String image1Path, String image2Path, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 56
   at DeveImageOptimizer.Helpers.ImageComparer.<>c__DisplayClass0_0.<AreImagesEqualAsync>b__0() in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 20
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(String fileToOptimize, String originDirectory) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\FileProcessing\FileOptimizerProcessor.cs:line 100
```

### Image 03_1.png

![03_1](https://user-images.githubusercontent.com/2350015/65526504-7e5cb400-def1-11e9-827d-94626566a34b.png)

```
03_1.png
Exception happened when optimizing or comparing the image:
SixLabors.ImageSharp.ImageFormatException: Invalid window size for ZLIB header: cinfo=12
   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at DeveImageOptimizer.Helpers.ImageComparer.LoadImageHelper(String imagePath, List`1 tempFiles, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 34
   at DeveImageOptimizer.Helpers.ImageComparer.AreImagesEqual(String image1Path, String image2Path, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 56
   at DeveImageOptimizer.Helpers.ImageComparer.<>c__DisplayClass0_0.<AreImagesEqualAsync>b__0() in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 20
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(String fileToOptimize, String originDirectory) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\FileProcessing\FileOptimizerProcessor.cs:line 100
```

#### Image 05.png

![05](https://user-images.githubusercontent.com/2350015/65526571-9df3dc80-def1-11e9-9da6-e4483a758f07.png)

```
05.png
Exception happened when optimizing or comparing the image:
SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=254
   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at DeveImageOptimizer.Helpers.ImageComparer.LoadImageHelper(String imagePath, List`1 tempFiles, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 34
   at DeveImageOptimizer.Helpers.ImageComparer.AreImagesEqual(String image1Path, String image2Path, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 56
   at DeveImageOptimizer.Helpers.ImageComparer.<>c__DisplayClass0_0.<AreImagesEqualAsync>b__0() in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 20
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(String fileToOptimize, String originDirectory) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\FileProcessing\FileOptimizerProcessor.cs:line 100
```

#### Image 05_3.png

![05_3](https://user-images.githubusercontent.com/2350015/65526641-ba901480-def1-11e9-86df-4b7b9fb686b8.png)

```
05_3.png
Exception happened when optimizing or comparing the image:
SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=1
   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at DeveImageOptimizer.Helpers.ImageComparer.LoadImageHelper(String imagePath, List`1 tempFiles, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 34
   at DeveImageOptimizer.Helpers.ImageComparer.AreImagesEqual(String image1Path, String image2Path, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 56
   at DeveImageOptimizer.Helpers.ImageComparer.<>c__DisplayClass0_0.<AreImagesEqualAsync>b__0() in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 20
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(String fileToOptimize, String originDirectory) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\FileProcessing\FileOptimizerProcessor.cs:line 100
```

#### Image 08_1.png

![08_1](https://user-images.githubusercontent.com/2350015/65526739-dc899700-def1-11e9-9274-4bb5b094a6d4.png)

```
08_1.png
Exception happened when optimizing or comparing the image:
SixLabors.ImageSharp.ImageFormatException: Invalid window size for ZLIB header: cinfo=15
   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at DeveImageOptimizer.Helpers.ImageComparer.LoadImageHelper(String imagePath, List`1 tempFiles, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 34
   at DeveImageOptimizer.Helpers.ImageComparer.AreImagesEqual(String image1Path, String image2Path, Boolean useImageSharpBugWorkaround) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 56
   at DeveImageOptimizer.Helpers.ImageComparer.<>c__DisplayClass0_0.<AreImagesEqualAsync>b__0() in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\Helpers\ImageComparer.cs:line 20
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DeveImageOptimizer.FileProcessing.FileOptimizerProcessor.OptimizeFile(String fileToOptimize, String originDirectory) in C:\XKanWeg\##TempImageOptimizerFailingImagesInvest\DeveImageOptimizer\DeveImageOptimizer\FileProcessing\FileOptimizerProcessor.cs:line 100
```

### Steps to Reproduce

Call `Image.Load<Rgba32>(imagePath);` on the images above.

### System Configuration

- ImageSharp version: 1.0.0-dev002988
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Windows 10 Enterprise
- .NET Framework version: 4.8
- Additional information:

**Comment by JimBobSquarePants** [comment]
It looks like we've hit a hard limitation of the .NET `DeflateStream` implementation. Turning off all sanitation code to ensure that the image matches the specification allows only partial decoding of some of the images.
 
![05](https://user-images.githubusercontent.com/385879/65610380-98cb8600-dff4-11e9-8463-0188f159dc26.png)
![05_3](https://user-images.githubusercontent.com/385879/65610382-98cb8600-dff4-11e9-86a0-0d1c9cc1b4ec.png)
![08_1](https://user-images.githubusercontent.com/385879/65610383-99641c80-dff4-11e9-853e-67ef86675e0e.png)

**Comment by JimBobSquarePants** [comment]
Fixed by the amazing @brianpopow !

**Comment by devedse** [comment]
Can confirm this is now fixed!
https://ci.appveyor.com/project/devedse/deveimageoptimizer/builds/28106287

**Comment by angelaki** [comment]
Should this be fixed with `1.0.3`. Still having this issue pretty much all the time with 50% of my images.

**Comment by brianpopow** [comment]
> Should this be fixed with `1.0.3`. Still having this issue pretty much all the time with 50% of my images.
> 
> I can provide some images, if required.

I dont get it. Have you tried 1.0.3 yet? Are there any failing images with `1.0.3`?

**Comment by angelaki** [comment]
Some images also throw this exception:

SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=229    at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk) in SixLabors.ImageSharp.dll:token 0x6001554+0x78    at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.AllocateNewBytes(Int32 bytes, Boolean isCriticalChunk) in SixLabors.ImageSharp.dll:token 0x600154c+0xf    at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata) in SixLabors.ImageSharp.dll:token 0x6001422+0x18    at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken) in SixLabors.ImageSharp.dll:token 0x6001418+0x0    at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.DecodeAsync[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken) in SixLabors.ImageSharp.dll:token 0x6001372+0x8 --- End of stack trace from previous location ---    at SixLabors.ImageSharp.Formats.Png.PngDecoder.DecodeAsync(Configuration configuration, Stream stream, CancellationToken cancellationToken) in SixLabors.ImageSharp.dll:token 0x6001411+0x7e    at SixLabors.ImageSharp.Image.DecodeAsync(Stream stream, Configuration config, CancellationToken cancellationToken) in SixLabors.ImageSharp.dll:token 0x60001a1+0x118    at SixLabors.ImageSharp.Image.<>c__DisplayClass134_0.<<LoadWithFormatAsync>b__0>d.MoveNext() in SixLabors.ImageSharp.dll:token 0x6002146+0x7d --- End of stack trace from previous location ---    at SixLabors.ImageSharp.Image.WithSeekableStreamAsync[T](Configuration configuration, Stream stream, Func`3 action, CancellationToken cancellationToken) in SixLabors.ImageSharp.dll:token 0x6000205+0xe6    at SixLabors.ImageSharp.Image.LoadWithFormatAsync(Configuration configuration, Stream stream, CancellationToken cancellationToken) in SixLabors.ImageSharp.dll:token 0x6000200+0xb1

...

**Comment by angelaki** [comment]
Just tested, it is a .Net 6.0 error! Oops ... Really need this right now. Someone willing / able to look under the hood?

**Comment by brianpopow** [comment]
> Just tested, it is a .Net 6.0 error! Oops ... Really need this right now. Someone willing / able to look under the hood?

This sounds like an issue we already have fixed #1707

You can try our nightly builds from here: [Nightly](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)

**Comment by angelaki** [comment]
Ah, thank you! I'll give it a try. Will they be _prereleased_ on nuget, too?

**Comment by brianpopow** [comment]
> Ah, thank you! I'll give it a try. Will they be _prereleased_ on nuget, too?

No, only stable releases on nuget. `2.0` is not far away though, but I cannot give any exact date.

**Comment by angelaki** [comment]
Working with your nightly, thank you so much!
