### ISSUE TITLE
IndexOutOfRange Exception in newest myget package

### ISSUE THREAD

**Issue by jogibear9988** [SixLabors/ImageSharp#1167]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I got this Stacktrace runnig my code:

![image](https://user-images.githubusercontent.com/364896/78508767-a32bc100-7789-11ea-8083-3e6473d85442.png)

It's crashing running this code:

                double dpi = 96;
                var factor = 4;
                var view = (Canvas)designSurface.DesignContext.RootItem.Component;
                designSurface.DesignContext.Services.Selection.SetSelectedComponents(null);
                using (var outputImage = new SixLabors.ImageSharp.Image<Rgba32>((int)view.ActualWidth * factor, (int)view.ActualHeight * factor))
                {
                    for (int xFac = 0; xFac < factor; xFac++)
                    {
                        for (int yFac = 0; yFac < factor; yFac++)
                        {
                            using (Stream stream = new MemoryStream())
                            {
                                var tcs = new TaskCompletionSource<bool>();
                                var tg = new TransformGroup();
                                tg.Children.Add(new ScaleTransform(factor, factor));
                                tg.Children.Add(new TranslateTransform(-(view.ActualWidth * xFac), -(view.ActualHeight * yFac)));
                                view.RenderTransform = tg;
                                Dispatcher.Invoke(new Action(() => tcs.SetResult(true)), System.Windows.Threading.DispatcherPriority.Render);
                                await tcs.Task;
                                Size size = new Size(view.ActualWidth, view.ActualHeight);
                                RenderTargetBitmap result = new RenderTargetBitmap((int)size.Width, (int)size.Height, dpi, dpi, PixelFormats.Pbgra32);
                                result.Render(view);
                                PngBitmapEncoder encoder = new PngBitmapEncoder();
                                encoder.Frames.Add(BitmapFrame.Create(result));
                                encoder.Save(stream);
                                stream.Flush();
                                stream.Position = 0;
                                using (var img1 = SixLabors.ImageSharp.Image.Load<Rgba32>(stream))
                                {
                                    outputImage.Mutate(o => o.DrawImage(img1, new SixLabors.ImageSharp.Point((int)view.ActualWidth * xFac, (int)view.ActualHeight * yFac), 1f));
                                }
                            }
                        }
                    }
                    using (Stream stream = new FileStream(dlg.FileName, FileMode.OpenOrCreate, FileAccess.ReadWrite))
                    {
                        outputImage.Save(stream, new PngEncoder());
                    }
                }
                view.RenderTransform = null;

in the outputImage.Mutate where the parameters for the point resolve to 0 and 20000

**Comment by JimBobSquarePants** [comment]
What is the size of the image and what are x and y when the exception is thrown?

**Comment by jogibear9988** [comment]
size is 80000x40000

point is 0 and 20000 so it means x is zero and y is 2

**Comment by JimBobSquarePants** [comment]
And what are the dimensions of the `im1` image?

**Comment by JimBobSquarePants** [comment]
Ok....

I'm able to reproduce the issue with the following code. 

``` c#
using (var image = new Image<Rgba32>(80000, 40000))
{
    image[0, 20000] = Color.Black; // I don't believe this is relevant.

    image.Save(Path.Combine(outPath, "massive.png"));
}
```

The stack trace is different but the final exception location is the same. I don't believe `DrawImage` or any pixel manipulation is relevant. 

``` bash
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SixLabors.ImageSharp.Memory.MemoryGroup`1.Owned.get_Item(Int32 index)
   at SixLabors.ImageSharp.Memory.MemoryGroupExtensions.GetBoundedSlice[T](IMemoryGroup`1 group, Int64 start, Int32 length)
   at SixLabors.ImageSharp.Memory.Buffer2D`1.GetRowMemorySlow(Int32 y)
   at SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.GetPixelRowSpan[TPixel](ImageFrame`1 source, Int32 rowIndex)
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.EncodePixels[TPixel](ImageFrame`1 pixels, IndexedImageFrame`1 quantized, ZlibDeflateStream deflateStream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.WriteDataChunks[TPixel](ImageFrame`1 pixels, IndexedImageFrame`1 quantized, Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoder.Encode[TPixel](Image`1 image, Stream stream)
   at SixLabors.ImageSharp.Image.EncodeVisitor.Visit[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Image`1.Accept(IImageVisitor visitor)
   at SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.AcceptVisitor(Image source, IImageVisitor visitor)
   at SixLabors.ImageSharp.Image.Save(Stream stream, IImageEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, String filePath, IImageEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, String filePath)
   at ImageSharp.Test.Program.Main() in C:\development\misc\ImageSharp.Test\ImageSharp.Test\Program.cs:line 31
   at ImageSharp.Test.Program.<Main>()
```

@antonfirsov one for you perhaps?

**Comment by antonfirsov** [comment]
Yeah, I'll look into it.
