### ISSUE TITLE
context.BackgroundColor throws Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TheMisir** [SixLabors/ImageSharp#1230]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

```
Object reference not set to an instance of an object.

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at SixLabors.ImageSharp.GraphicOptionsDefaultsExtensions.GetGraphicsOptions(Configuration configuration)
   at SixLabors.ImageSharp.GraphicOptionsDefaultsExtensions.GetGraphicsOptions(IImageProcessingContext context)
   at SixLabors.ImageSharp.Processing.BackgroundColorExtensions.BackgroundColor(IImageProcessingContext source, Color color)
   at Dropmaker.Program.<RunOnce>b__12_0(IImageProcessingContext ctx) in C:\Users\misir\source\repos\Dropmarker\src\Program.cs:line 280
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.ProcessingVisitor.Visit[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Image`1.Accept(IImageVisitor visitor)
   at SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.AcceptVisitor(Image source, IImageVisitor visitor)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate(Image source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate(Image source, Action`1 operation)
   at Dropmaker.Program.RunOnce(State state) in C:\Users\misir\source\repos\Dropmarker\src\Program.cs:line 278
```

### Steps to Reproduce

It happens sometimes when I compile & run this code.

```csharp
var image = Image.Load("image.jpg");
image.Mutate(ctx =>
{
    ctx.BackgroundColor(Color.White);
});
```

### System Configuration

- ImageSharp version: SixLabors.ImageSharp@1.0.0-rc0002
- Environment (Operating system, version and so on): Windows 10 x64
- .NET Framework version: .NET Core 3.1

**Comment by JimBobSquarePants** [comment]
> It happens sometimes when I compile & run this code.

What do you mean by this, Is the issue intermittent? What environmental factors trigger a difference in result.

**Comment by TheMisir** [comment]
> What do you mean by this, Is the issue intermittent? What environmental factors trigger a difference in result.

I really don't know what triggers the issue. Might be because of multithreaded process or something else. In case you're interested here's source code of the project: [Program.cs:288](https://github.com/TheMisir/dropmaker/blob/master/src/Program.cs#L288). There might be some sort of low level issue which caused this code to throw an exception.

```csharp
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
```

> Are you running this in multiple threads?

Yes, I'm using ImageSharp to process thousands of images by using multiple threads.

**Comment by JimBobSquarePants** [comment]
> Yes. I did run this code in multiple threads to reduce time since I need to process thousands of images.

Thanks @TheMisir that's correlates with my findings. If got a fix in motion. #1234
