### ISSUE TITLE
Magick.NET 7.22.0 Fails to decode some BMP images on Ubuntu

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp#1380]
See https://github.com/SixLabors/ImageSharp/runs/1249800746?check_suite_focus=true#step:6:350

```
Error Message:
   ImageMagick.MagickCorruptImageErrorException : LengthAndFilesizeDoNotMatch `' @ error/bmp.c/ReadBMPImage/845
  Stack Trace:
     at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(IMagickSettings`1 settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, IMagickReadSettings`1 readSettings, Boolean ping)
   at SixLabors.ImageSharp.Tests.TestUtilities.ReferenceCodecs.MagickReferenceDecoder.Decode[TPixel](Configuration configuration, Stream stream) in /home/runner/work/ImageSharp/ImageSharp/tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs:line 57
   at SixLabors.ImageSharp.Image.<>c__DisplayClass130_0`1.<Load>b__0(Stream s) in /_/src/ImageSharp/Image.FromStream.cs:line 481
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageDecoder decoder) in /_/src/ImageSharp/Image.FromStream.cs:line 481
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, String path, IImageDecoder decoder) in /_/src/ImageSharp/Image.FromFile.cs:line 516
   at SixLabors.ImageSharp.Image.Load[TPixel](String path, IImageDecoder decoder) in /_/src/ImageSharp/Image.FromFile.cs:line 493
   at SixLabors.ImageSharp.Tests.TestImageExtensions.VerifyEncoder[TPixel](Image`1 image, ITestImageProvider provider, String extension, Object testOutputDetails, IImageEncoder encoder, ImageComparer customComparer, Boolean appendPixelTypeToFileName, String referenceImageExtension, IImageDecoder referenceDecoder) in /home/runner/work/ImageSharp/ImageSharp/tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs:line 659
   at SixLabors.ImageSharp.Tests.Formats.Bmp.BmpEncoderTests.TestBmpEncoderCore[TPixel](TestImageProvider`1 provider, BmpBitsPerPixel bitsPerPixel, Boolean supportTransparency, ImageComparer customComparer) in /home/runner/work/ImageSharp/ImageSharp/tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs:line 271
   at SixLabors.ImageSharp.Tests.Formats.Bmp.BmpEncoderTests.Encode_8BitGray_WithV3Header_Works[TPixel](TestImageProvider`1 provider, BmpBitsPerPixel bitsPerPixel) in /home/runner/work/ImageSharp/ImageSharp/tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs:line 171
```

Previous versions worked but were incompatible with latest VS test runner versions. 

CI tests will be disabled on this platform until we can provide a fix.

**Comment by JimBobSquarePants** [comment]
Reopening to track upstream dependency issue.

**Comment by dlemstra** [comment]
The delta appears to be pretty big (custom error message):

```
identify: File size: 9270, bmp header data: 8246 Encode_8Bit_WithV3Header_Works_Rgba32_pal8-0_Pixel8.bmp' @ error/bmp.c/ReadBMPImage/845.
identify: File size: 9270, bmp header data: 8246 Encode_8Bit_WithV3Header_Works_Rgba32_pal8v5_Pixel8.bmp' @ error/bmp.c/ReadBMPImage/845.
identify: File size: 9338, bmp header data: 8314 Encode_8Bit_WithV4Header_Works_Rgba32_pal8-0_Pixel8.bmp' @ error/bmp.c/ReadBMPImage/845.
identify: File size: 9338, bmp header data: 8314 Encode_8Bit_WithV4Header_Works_Rgba32_pal8v5_Pixel8.bmp' @ error/bmp.c/ReadBMPImage/845.
identify: File size: 9270, bmp header data: 8246 Encode_8BitGray_WithV3Header_Works_L8_pal8gs_Pixel8.bmp' @ error/bmp.c/ReadBMPImage/845.
identify: File size: 9338, bmp header data: 8314 Encode_8BitGray_WithV4Header_Works_L8_pal8gs_Pixel8.bmp' @ error/bmp.c/ReadBMPImage/845.
```

It is 1024 for all cases.
