### ISSUE TITLE
Sporadic AccessViolation in MagickReferenceDecoder with Issue695-Invalid-EOI.jpg

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1461]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The error seems to be rare, I couldn't repro it locally now, but people and CI keeps hitting it time to time, so I believe it's worth to use the issue tracker as our extended memory.

/cc @dlemstra 

### Steps to Reproduce
Run JpegDecoder tests on `net472` + 32 bit with different runners. `MagickReferenceDecoder` seems to fail for `Issue695-Invalid-EOI.jpg`.

**Comment by antonfirsov** [comment]
Have a stack trace from CI:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImageMagick.PixelCollection.NativeMethods.X86.PixelCollection_ToByteArray(IntPtr Instance, UIntPtr x, UIntPtr y, UIntPtr width, UIntPtr height, IntPtr mapping, IntPtr& exception)
   at ImageMagick.PixelCollection.NativePixelCollection.ToByteArray(Int32 x, Int32 y, Int32 width, Int32 height, String mapping)
   at ImageMagick.PixelCollection.ToByteArray(Int32 x, Int32 y, Int32 width, Int32 height, String mapping)
   at ImageMagick.UnsafePixelCollection.ToByteArray(Int32 x, Int32 y, Int32 width, Int32 height, String mapping)
   at ImageMagick.PixelCollection.ToByteArray(PixelMapping mapping)
   at SixLabors.ImageSharp.Tests.TestUtilities.ReferenceCodecs.MagickReferenceDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass130_0`1.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageDecoder decoder)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, String path, IImageDecoder decoder)
   at SixLabors.ImageSharp.Tests.TestImageExtensions.GetReferenceOutputImage[TPixel](ITestImageProvider provider, Object testOutputDetails, String extension, Boolean appendPixelTypeToFileName, Boolean appendSourceFileOrDescription, IImageDecoder decoder)
   at SixLabors.ImageSharp.Tests.TestImageExtensions.CompareToReferenceOutput[TPixel](Image`1 image, ImageComparer comparer, ITestImageProvider provider, Object testOutputDetails, String extension, Boolean grayscale, Boolean appendPixelTypeToFileName, Boolean appendSourceFileOrDescription, IImageDecoder decoder)
   at SixLabors.ImageSharp.Tests.Formats.Jpg.JpegDecoderTests.<DecodeBaselineJpeg>g__RunTest|0_0[TPixel](String providerDump, String nonContiguousBuffersStr)
   at SixLabors.ImageSharp.Tests.Formats.Jpg.JpegDecoderTests.DecodeBaselineJpeg[TPixel](TestImageProvider`1 provider, Boolean enforceDiscontiguousBuffers)
```

**Comment by dlemstra** [comment]
It looks like an upgrade of Magick.NET resolved this issue. Can we close this issue @JimBobSquarePants?

**Comment by JimBobSquarePants** [comment]
Yeah. Haven’t seen it since.
