### ISSUE TITLE
System.ArgumentOutOfRangeException when loading a valid PNG image

### ISSUE THREAD

**Issue by QuantumToasted** [SixLabors/ImageSharp#1529]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

This seems to be very similar to #1482, which seems to have been closed because the author was unfortunately not able to provide a copy of the original image in question? The exception is the same, but I'm not sure if the cause is.

When attempting to load the following PNG,
![thinking](https://user-images.githubusercontent.com/30324210/106539831-58bbc380-64c4-11eb-8810-f6cd33003d5b.png)
via the following lines of code,
```cs
// doc is an SvgDocument from https://github.com/svg-net/SVG
// bitmap is a System.Drawing.Bitmap
using var bitmap = doc.Draw();
await using var output = new MemoryStream();
bitmap.Save(output, ImageFormat.Png);
output.Seek(0, SeekOrigin.Begin);
var image = Image.Load<Rgba32>(stream, new PngDecoder());
```
The following exception is thrown:
```
System.ArgumentOutOfRangeException: Parameter "Position" (System.Int64) must be less than or equal to 1573, was 1581 (Parameter 'Position')
   at SixLabors.ThrowHelper.ThrowArgumentOutOfRangeException(String name, String message)
   at SixLabors.ThrowHelper.ThrowArgumentOutOfRangeExceptionForMustBeLessThanOrEqualTo[T](T value, T maximum, String name)
   at SixLabors.ImageSharp.IO.BufferedReadStream.set_Position(Int64 value)
   at SixLabors.ImageSharp.StreamExtensions.Skip(Stream stream, Int32 count)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass128_0`1.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream, IImageDecoder decoder)
```

I'm not sure if it has something to do with System.Drawing and ImageSharp disagreeing on what is a PNG, as the SVG library I am using only supports System.Drawing, so I have to export it via that, and then load it into ImageSharp.

### Steps to Reproduce

Since this depends on another C# library, I can understand that the SVG library I am using may be to blame.
However, when I save the `output` stream to a file instead of trying to load it into ImageSharp, it is able to save to what seems to be a valid PNG file. I have not tried loading this saved file directly. I will update this issue with a test which loads the file directly instead of depending on the SVG library, but I couldn't see what the difference would be.

**Edit: I saved the raw `output` stream to a file, loaded it into a stream, and then again loaded it as an Image. I...don't know why, but it works fine. The `output` stream in the failing code and the loaded stream in the separate test look to have identical data. I will work on a lightweight test project soon if this cannot be repro'd locally.*

### System Configuration

- ImageSharp version: `1.0.3-alpha.0.29`
- Other ImageSharp packages and versions: `ImageSharp.Drawing 1.0.0-beta11.4`
- Environment (Operating system, version and so on): Windows 10 x64
- .NET Framework version: .NET 5.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
@QuantumToasted Your test code is attempting to load the wrong stream 'stream' should be 'output'.

``` c#
// doc is an SvgDocument from https://github.com/svg-net/SVG
// bitmap is a System.Drawing.Bitmap
using var bitmap = doc.Draw();
await using var output = new MemoryStream();
bitmap.Save(output, ImageFormat.Png);
output.Seek(0, SeekOrigin.Begin);

// This should be 'output' not 'stream'
var image = Image.Load<Rgba32>(stream, new PngDecoder());
```
