### ISSUE TITLE
load gif   System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)

### ISSUE THREAD

**Issue by 3400442579** [SixLabors/ImageSharp#1530]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at SixLabors.ImageSharp.Memory.Buffer2DRegion`1.Clear()
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.RestoreToBackground[TPixel](ImageFrame`1 frame)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrameColors[TPixel](Image`1& image, ImageFrame`1& previousFrame, Buffer2D`1 indices, ReadOnlySpan`1 colorTable, GifImageDescriptor& descriptor)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrame[TPixel](Image`1& image, ImageFrame`1& previousFrame)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, String path, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(String path)
   at GifClient.ViewModels.CropViewModel.<>c__DisplayClass38_0.<SaveAsync>b__1() in E:\lq\GifAdvanced\src\BlueClient\ViewModels\CropViewModel.cs:line 177

### Steps to Reproduce
 try
                {
                    Image gimage = Image.Load(sourceGif);
                    //gimage.Mutate(o => o.Crop(new Rectangle(Rect.X, Rect.Y, Rect.Width, Rect.Height)));
                    //gimage.SaveAsGif(fn);
                }

### System Configuration

- ImageSharp version: 1.0.2
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): win10
- .NET Framework version: 4.7.2
- Additional information:

gif file:
![aa](https://user-images.githubusercontent.com/34226979/106542849-8d209580-653f-11eb-8b27-899de0f8b771.gif)

**Comment by JimBobSquarePants** [comment]
I'll take this. It's due to bad descriptor bounds in the image defining a rectangle outside of the frame bounds. 

Fix is easy enough. Use `Rectangle.Intersect` to sanitize the value before requesting a rectangle from the buffer.
