### ISSUE TITLE
GIF parsing failure: throws IndexOutOfRange on ReadFrameColors

### ISSUE THREAD

**Issue by TETYYS** [SixLabors/ImageSharp#1668]
### Description
Looks to be similar to https://github.com/SixLabors/ImageSharp/issues/403

Image.Load throws a System.IndexOutOfRangeException exception when loading this gif:
![1x](https://user-images.githubusercontent.com/3091645/122422137-957ce880-cf95-11eb-9a38-fd19aadce5f2.gif)

```
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrameColors[TPixel](Image`1& image, ImageFrame`1& previousFrame, Buffer2D`1 indices, ReadOnlySpan`1 colorTable, GifImageDescriptor& descriptor)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrame[TPixel](Image`1& image, ImageFrame`1& previousFrame)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass137_0.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Load(Stream stream)
   at <Program>$.<<Main>$>d__0.MoveNext() in Program.cs:line 9
```

### Steps to Reproduce
```
using SixLabors.ImageSharp;
using System;
using System.Net.Http;

var http = new HttpClient();
var stream = await http.GetStreamAsync("https://user-images.githubusercontent.com/3091645/122422137-957ce880-cf95-11eb-9a38-fd19aadce5f2.gif");

var image = Image.Load(stream);

Console.WriteLine(image.Height);
```

### System Configuration
Same error both on linux and windows, so I don't think this matters

- ImageSharp version: 1.0.3 (nuget)
- Environment (Operating system, version and so on): Any
- .NET Framework version: net5.0

**Comment by brianpopow** [comment]
It dont think its related to #403. It seems that the frame 16 has an invalid color index present.
