### ISSUE TITLE
Error with Image.Load

### ISSUE THREAD

**Issue by KANekT** [SixLabors/ImageSharp#178]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode

### Steps to Reproduce
` 
var image = Image.Load(file.OpenReadStream());
`

I have error Too many coefficients 64 > 63 for [file/link](https://data.yougile.com/user-data/c989b56d-b0b7-4e1d-a048-c8f22ad0ec44/lemon.jpg)

`   at ImageSharp.Formats.Jpg.JpegScanDecoder.Refine(InputProcessor& bp, HuffmanTree& h, Int32 delta)
   at ImageSharp.Formats.Jpg.JpegScanDecoder.DecodeBlock(JpegDecoderCore decoder, Int32 scanIndex)
   at ImageSharp.Formats.Jpg.JpegScanDecoder.DecodeBlocks(JpegDecoderCore decoder)
   at ImageSharp.Formats.JpegDecoderCore.ProcessStartOfScan(Int32 remaining)
   at ImageSharp.Formats.JpegDecoderCore.ProcessStream(ImageMetaData metadata, Stream stream, Boolean metadataOnly)
   at ImageSharp.Formats.JpegDecoderCore.Decode[TColor](Stream stream)
   at ImageSharp.Formats.JpegDecoder.Decode[TColor](Configuration configuration, Stream stream, IDecoderOptions options)
   at ImageSharp.Image.Decode[TColor](Stream stream, IDecoderOptions options, Configuration config)
   at ImageSharp.Image.Load[TColor](Configuration config, Stream stream, IDecoderOptions options)
   at ImageSharp.Image.Load(Stream stream)
   at Biggab.Game.Education.Backend.ViewModels.Words.CreateOrEditViewModelFactory.<SaveFile>d__5.MoveNext() in C:\Projects\BiggabSocial\src\Biggab.Game.Education.Backend\Areas\Backend\ViewModels\Words\CreateOrEditViewModelFactory.cs:line 99`
### System Configuration

- ImageSharp version: 1.0.0-alpha9-00025
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10 VS 2015
- .NET Framework version: 1.2
- Additional information:

**Comment by tocsoft** [comment]
Look like it's an image specific issue, Please provide a copy of the image that causes this issue.

**Comment by antonfirsov** [comment]
@tocsoft he has a link in the issue description :)

**Comment by tocsoft** [comment]
My bad, failed to spot the link.

**Comment by jonatan280792** [comment]
Me sucede
![bmw-m3-m3-f80-lujo-D_NQ_NP_948620-MCO31407881656_072019-F](https://user-images.githubusercontent.com/54013509/99834788-bb422c00-2b31-11eb-8d54-551e4183a221.png)
 el mismo error adjunto imagen

**Comment by antonfirsov** [comment]
@jonatan280792 if you feel you found a bug in the [**CURRENT**](https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.2) ImageSharp version, please open a new issue with **the issue template filled** + image attached, we can't address feedback coming from comments on old issues.

Si el idioma es un problema, use el traductor de Google como lo hago ahora :)

**Comment by JimBobSquarePants** [comment]
That linked image is a png.
