### ISSUE TITLE
gif  crop: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by 3400442579** [SixLabors/ImageSharp#1880]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageSharp version:1.0.3
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):win10
- .NET Framework version:5.0.4
- Additional information:

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Buffers.ConfigurableArrayPool`1.Rent(Int32 minimumLength)
   at SixLabors.ImageSharp.Memory.ArrayPoolMemoryAllocator.Allocate[T](Int32 length, AllocationOptions options)
   at SixLabors.ImageSharp.Memory.MemoryGroup`1.Allocate(MemoryAllocator allocator, Int64 totalLength, Int32 bufferAlignment, AllocationOptions options)
   at SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.Allocate2D[T](MemoryAllocator memoryAllocator, Int32 width, Int32 height, AllocationOptions options)
   at SixLabors.ImageSharp.ImageFrame`1..ctor(Configuration configuration, ImageFrame`1 source)
   at SixLabors.ImageSharp.ImageFrameCollection`1.AddFrame(ImageFrame`1 source)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrameColors[TPixel](Image`1& image, ImageFrame`1& previousFrame, Buffer2D`1 indices, ReadOnlySpan`1 colorTable, GifImageDescriptor& descriptor)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrame[TPixel](Image`1& image, ImageFrame`1& previousFrame)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass137_0.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, String path, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, String path)
   at SixLabors.ImageSharp.Image.Load(String path)

**Comment by JimBobSquarePants** [comment]
Thanks for the stack trace but we're really going to need the steps to reproduce as dictated by the image template. 

It's also a requirement that you are using the latest version of the library. That as of now is v1.0.4 not v1.0.3

**Comment by antonfirsov** [comment]
@3400442579 can you try if it still fails with the latest nightlies?
https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp
