### ISSUE TITLE
SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=80 when loading png image

### ISSUE THREAD

**Issue by deMD** [SixLabors/ImageSharp#1939]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using Umbraco 9 on Azure Web Apps using Azure Storage to save media I get the following exception in ImageSharp:
```
SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=80

   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk)

   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)

   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)

   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)

   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream)

   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)

   at SixLabors.ImageSharp.Image.<>c__DisplayClass133_0`1.<Load>b__0(Stream s)

   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)

   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<>c__DisplayClass18_0.<<ProcessRequestAsync>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<>c__DisplayClass18_0.<<ProcessRequestAsync>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at SixLabors.ImageSharp.Web.Middleware.ConcurrentDictionaryExtensions.GetOrAddAsync[TKey,TValue](ConcurrentDictionary`2 dictionary, TKey key, Func`2 valueFactory)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)

   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   ```
   
This issue seems to only be caused when using Azure/Azure storage. When running on localhost with Azure Storage emulator as media storage the image does load without problems.

### Steps to Reproduce
Not available as I don't know exactly in what circumstances the issues occur. I do know this images doesn't show up when using query parameters on our development environment running in the configuration mentioned below: https://www.wearetriple.com/media/qfsl0o2c/vodafone-header-image-triple.png

### System Configuration
Azure Web App S1 tier
Standard LRS Tier Azure Storage
.Net 6

- ImageSharp version: 1.0.4
- Other ImageSharp packages and versions: SixLabors.ImageSharp.Web.Providers.Azure 1.0.3
- Environment (Operating system, version and so on): Azure Web App running Windows
- .NET Framework version: .Net 6
- Additional information: I use Umbraco 9 as cms.

**Comment by JimBobSquarePants** [comment]
Hi @deMD 

I'm not able to replicate this with the supplied image.

I'm definitely able to decode and process the image from an Azure blob Storage source using the SixLabors.ImageSharp.Web.Providers.Azure v1.0.5 builds which target ImageSharp v1.0.4.

![image](https://user-images.githubusercontent.com/385879/149251402-41a8e456-fcaf-49d2-8460-4e646e267590.png)

Please note. It's really important when raising an issue to be using the latest available NuGet versions.
