### ISSUE TITLE
Tiniest gif (ever) seems to trip up the GifDecoder

### ISSUE THREAD

**Issue by ericnewton76** [SixLabors/ImageSharp#1962]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
```c#
public static byte[] StringToByteArray(String hex)
{
	int NumberChars = hex.Length;
	byte[] bytes = new byte[NumberChars / 2];
	for (int i = 0; i < NumberChars; i += 2) { bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16); }
	return bytes;
}

var tiniestgif = new MemoryStream(StringToByteArray("4749463839610100010000ff002c00000000010001000002003b"));

var imageformat = SixLabors.ImageSharp.Image.DetectFormat(tiniestgif);

var image = SixLabors.ImageSharp.Image.Load(tiniestgif); //fails

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrame[TPixel](Image`1& image, ImageFrame`1& previousFrame)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass137_0.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Stream stream, IImageFormat& format)
   at SharingMemoriesWeb.Services.ImageService.GenerateThumbnail(Stream imagebytes, Size targetSize, Stream output) in C:\Projects\Arbor-Web-Apps\SharingMemories\Develop\SharingMemoriesWeb\Services\IImageService.cs:line 103
   at SharingMemoriesWeb.Services.ImageService.GenerateAdditional(BlobCacheInfo blob, Stream imageBytes, SizeType targetSize, Stream output, ArborContext db, Int32& blobId) in C:\Projects\Arbor-Web-Apps\SharingMemories\Develop\SharingMemoriesWeb\Services\IImageService.cs:line 91
   at SharingMemoriesWeb.Components.ImageBlobResult.ExecuteResult(ControllerContext context) in C:\Projects\Arbor-Web-Apps\SharingMemories\Develop\SharingMemoriesWeb\Components\ImageBlobResult.cs:line 133
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

```

Incidentally, tried to run this on dotnetfiddle but theres some typeinitialization errors and security problems when running there...
https://dotnetfiddle.net/4aLgnx

Of note, these came from: http://probablyprogramming.com/2009/03/15/the-tiniest-gif-ever

### System Configuration
Standard windows c# 

- ImageSharp version: **1.0.4**
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): **Windows 10, VS 2019,** 
- .NET Framework version: **4.7.2**
- Additional information:

Attachment:
[tiniest_gif_1st.zip](https://github.com/SixLabors/ImageSharp/files/7960708/tiniest_gif_1st.zip)

**Comment by JimBobSquarePants** [comment]
Can you please supply the gif in a format that is easily testable?

**Comment by dlemstra** [comment]
Probably caused by the image not having a color table at all.

**Comment by ericnewton76** [comment]
Sure.  I thought i had uploaded it, mustve got lost in translation [durp]
![tiniest_gif_1st](https://user-images.githubusercontent.com/2211788/151594749-297ada23-49de-438c-9d83-08ec62de6b68.gif)

**Comment by ericnewton76** [comment]
I forked the repo to try to build tests against it, but got a lot of language feature errors.  C# 8.0.  Fixed some of them by manually adding ```<LanguageFeatures>8.0</LanguageFeatures>``` to csproj, but still getting a lot of errors building the ImageSharp.Tests in VS2019.  Updated to latest VS2019 currently (16.11.9) and will try again

**Comment by JimBobSquarePants** [comment]
You need the submodules. It’s all in the repo readme
