### ISSUE TITLE
Memory leaks when watermarking images (Especially with GIFs)

### ISSUE THREAD

**Issue by BaileyMillerSSI** [SixLabors/ImageSharp#2079]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.0

### Other ImageSharp packages and versions

<PackageReference Include="SixLabors.Fonts" Version="1.0.0-beta16" /> <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />

### Environment (Operating system, version and so on)

Window 11 Pro, Version	10.0.22000 Build 22000

### .NET Framework version

net6.0

### Description

When watermarking images using the code below, I see a small uptick in RAM usage over time with PNGs/JPEGs and a huge RAM uptick with GIFs. I understand that during processing RAM will spike but because everything is wrapped in using statements, I would expect it to return to normal and flat line after an image is done. 

I also notice that the `MemoryDiagnostics.TotalUndisposedAllocationCount` increases by 20-100 per image processed.
![image](https://user-images.githubusercontent.com/14271740/162355243-6e1199d5-cd0f-429d-b200-1be7cef18cba.png)

On my system when processing certain GIFs I see spikes of 1GB that never go back down. 

### Steps to Reproduce

Program.sc:

```
public static class Program
{
    public static async Task Main(string[] args)
    {
        var builder = new HostBuilder()
            .ConfigureDefaults(args)
            .ConfigureServices((hostContext, services) =>
            {
                services.AddHttpClient();

                services.AddMassTransit(x =>
                {
                    x.UsingRabbitMq((context, cfg) =>
                    {
                        cfg.Host("localhost", "/", h =>
                        {
                            h.Username("guest");
                            h.Password("guest");
                        });

                        cfg.ConfigureEndpoints(context);
                    });

                    x.AddConsumers(typeof(Program).Assembly);
                });
            })
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging
                    .ClearProviders()
                    .AddFilter("Microsoft", LogLevel.Warning)
                    .AddFilter("System", LogLevel.Warning)
                    .AddConsole();
            });

        await builder.RunConsoleAsync();
    }
}
```

-----------------------------------------------

Consumer (I am using MassTransit but this can be any class/code in a loop etc.)

```
public class WatermarkImageConsumer
    : IConsumer<IFileCreated>
{
    private readonly HttpClient _httpClient;
    private readonly ILogger<WatermarkImageConsumer> _logger;

    private const string WatermarkFont = "Segoe Print";
    private const float WatermarkFontSize = 64f;

    public WatermarkImageConsumer(
        IHttpClientFactory factory,
        ILogger<WatermarkImageConsumer> logger)
    {
        _httpClient = factory.CreateClient();
        _minioClient = client;
        _logger = logger;
    }

    public async Task Consume(ConsumeContext<IFileCreated> context)
    {
        var startTime = DateTime.Now;
        var fileName = context.Message.Records.FirstOrDefault().S3.ObjectData.FileName;

        try
        {
            _logger.LogInformation($"Number of undisposed ImageSharp buffers: {MemoryDiagnostics.TotalUndisposedAllocationCount}");

            _logger.LogInformation($"Starting to process: {fileName}");

            using (var imageStream = await _httpClient
                .GetStreamAsync("Image Link")
            {
                var (image, format) = await Image.LoadWithFormatAsync(stream: imageStream);

                if (!SystemFonts.TryGet(WatermarkFont, out var fontFamily))
                    throw new Exception($"Couldn't find font {WatermarkFont}");

                var font = fontFamily.CreateFont(WatermarkFontSize, FontStyle.Regular);

                var options = new TextOptions(font)
                {
                    Dpi = 72,
                    KerningMode = KerningMode.Normal
                };

                var text = $"®️Watermark {DateTime.Today.Year}";

                var rect = TextMeasurer.Measure(text, options);

                image.Mutate(x => x.DrawText(
                    text,
                    font,
                    new Color(Rgba32.ParseHex("#FFFFFFEE")),
                    new PointF(image.Width / 2 - rect.Width / 2, image.Height / 2 - rect.Height / 2)));

                using (var memFile = new MemoryStream())
                {
                    await image.SaveAsync(memFile, format);

                    memFile.Position = 0;

                    // Save to outside location
                }

                image.Dispose();
            }

            _logger.LogInformation($"Number of undisposed ImageSharp buffers: {MemoryDiagnostics.TotalUndisposedAllocationCount}");
            GC.Collect();
        }
        catch (UnknownImageFormatException imageFormatException)
        {
            _logger.LogError(imageFormatException, "Image Error");
        }
        finally
        {
            _logger.LogInformation($"Finished processing {fileName}, duration: {DateTime.Now - startTime}");
        }
    }
}

public class WatermarkerImageConsumerDefinition :
    ConsumerDefinition<WatermarkImageConsumer>
{
    protected override void ConfigureConsumer(IReceiveEndpointConfigurator endpointConfigurator,
        IConsumerConfigurator<WatermarkImageConsumer> consumerConfigurator)
    {
        // configure message retry with millisecond intervals
        endpointConfigurator.UseMessageRetry(r => r.Intervals(TimeSpan.FromSeconds(5)));

        endpointConfigurator.PrefetchCount = 16;
        endpointConfigurator.ConcurrentMessageLimit = 1;
    }
}
```

### Images

This is a large GIF so here is a OneDrive link (https://1drv.ms/u/s!Ap2tk0ynKqQsoL5OWc87O7JAonq5Zw?e=AS212S).

Here is a random image as well:
![2021-12-29 (2)](https://user-images.githubusercontent.com/14271740/162356003-5dd78adc-f07d-4b9c-9df2-231cd0a9940d.png)

**Comment by JimBobSquarePants** [comment]
@BaileyMillerSSI Is this replicable without using an external service. 

I.E Would creating a console application simply loading and looping the same image replicate the issue?

**Comment by BaileyMillerSSI** [comment]
I think a small console app that loads the stream from the file system would likely produce a similar outcome. For that GIF you just need to run it once to see the massive RAM spike.

**Comment by BaileyMillerSSI** [comment]
@JimBobSquarePants 

Maybe I am missing something but with these using statements I expect to see RAM going up and down per image processed. Specifically for my use case in a consumer pipeline I cannot have RAM skyrocketing and only going up over time. 

Something like this seems to reproduce it as well:

```
const string WatermarkFont = "Segoe Print";
            const float WatermarkFontSize = 64f;

            foreach (var item in Enumerable.Range(0, 10))
            {
                using (var imageStream = File.OpenRead(@"DFUnVGJUEI.gif"))
                {
                    var (image, format) = await Image.LoadWithFormatAsync(stream: imageStream);

                    if (!SystemFonts.TryGet(WatermarkFont, out var fontFamily))
                        throw new Exception($"Couldn't find font {WatermarkFont}");

                    var font = fontFamily.CreateFont(WatermarkFontSize, FontStyle.Regular);

                    var options = new TextOptions(font)
                    {
                        Dpi = 72,
                        KerningMode = KerningMode.Normal
                    };

                    var text = $"®️Watermark {DateTime.Today.Year}";

                    var rect = TextMeasurer.Measure(text, options);

                    image.Mutate(x => x.DrawText(
                        text,
                        font,
                        new Color(Rgba32.ParseHex("#FFFFFFEE")),
                        new PointF(image.Width / 2 - rect.Width / 2, image.Height / 2 - rect.Height / 2)));

                    using (var memFile = new MemoryStream())
                    {
                        await image.SaveAsync(memFile, format);

                        memFile.Position = 0;
                    }

                    image.Dispose();
                }
                GC.Collect();
            }
```

**Comment by JimBobSquarePants** [comment]
You're definitely gonna get increased RAM usage doing this inside a loop. Nothing is pooled here plus your exception would cause `image.Dispose()` to never be called.

```c#
 if (!SystemFonts.TryGet(WatermarkFont, out var fontFamily))
        throw new Exception($"Couldn't find font {WatermarkFont}");

    var font = fontFamily.CreateFont(WatermarkFontSize, FontStyle.Regular);
```

We will over-request memory from the pool when reading async streams since we have to copy the stream response internally to make the request non-blocking and there's a chance of exhausting `ArrayPool.Shared<byte>` with lots of concurrent requests. This would lead to memory increase only reclaimed by the GC. We have tried to mitigate this using custom pooling logic but it could still potentially be an issue. 

I'd be very curious to see the difference between sync/async.

We might be leaking though but would require profiling the application to see where.

**Comment by BaileyMillerSSI** [comment]
I am still seeing a continuous increase in buffers per loop run as well as really high RAM usage with this code as well:

![image](https://user-images.githubusercontent.com/14271740/162364627-4d044648-b545-474a-b69e-302bddbe1c4a.png)

One thing to note I like this test because I have noticed running the same image repeatedly doesn't leak as much. In my setup I need the image to be unique per loop because that's how it will be in my production setup.

![image](https://user-images.githubusercontent.com/14271740/162364866-84f21946-7feb-4e21-b8de-414c7b73f3c8.png)


```
const string WatermarkFont = "Segoe Print";
const float WatermarkFontSize = 64f;

if (!SystemFonts.TryGet(WatermarkFont, out var fontFamily))
    throw new Exception($"Couldn't find font {WatermarkFont}");

var font = fontFamily.CreateFont(WatermarkFontSize, FontStyle.Regular);

var options = new TextOptions(font)
{
    Dpi = 72,
    KerningMode = KerningMode.Normal
};

foreach (var path in Directory.EnumerateFiles(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures), "*.gif", SearchOption.AllDirectories))
{
    using (var imageStream = File.OpenRead(path))
    {

        Console.WriteLine($"File Size: {imageStream.Length}");

        var (image, format) = await Image.LoadWithFormatAsync(stream: imageStream);

        var text = $"®️Watermark {DateTime.Today.Year}";

        var rect = TextMeasurer.Measure(text, options);

        image.Mutate(x => x.DrawText(
            text,
            font,
            new Color(Rgba32.ParseHex("#FFFFFFEE")),
            new PointF(image.Width / 2 - rect.Width / 2, image.Height / 2 - rect.Height / 2)));

        using (var memFile = new MemoryStream())
        {
            await image.SaveAsync(memFile, format);

            memFile.Position = 0;
        }

        image.Dispose();
    }
    Console.WriteLine($"Number of undisposed ImageSharp buffers: {MemoryDiagnostics.TotalUndisposedAllocationCount}");
    GC.Collect();
}
```

**Comment by JimBobSquarePants** [comment]
Just did a bit of experimentation running several different mutations (not done any memory profiling yet) but it looks like the leak is related to `DrawText`.

**Comment by br3aker** [comment]
It's `DrawText` indeed, here's an example stacktrace of undisposed allocations for some random gif `kumin.gif` from test suit. Given image have 20 leaks and all of them come from `SixLabors.ImageSharp.Drawing.InternalPath.ExtractVertices(MemoryAllocator allocator)`:

```
   at System.Environment.get_StackTrace()
   at SixLabors.ImageSharp.Memory.Internals.RefCountedMemoryLifetimeGuard..ctor()
   at SixLabors.ImageSharp.Memory.Internals.SharedArrayPoolBuffer`1.LifetimeGuard..ctor(Byte[] array)
   at SixLabors.ImageSharp.Memory.Internals.SharedArrayPoolBuffer`1..ctor(Int32 lengthInElements)
   at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator.Allocate[T](Int32 length, AllocationOptions options)
   at SixLabors.ImageSharp.Drawing.InternalPath.ExtractVertices(MemoryAllocator allocator)
   at SixLabors.ImageSharp.Drawing.Shapes.TessellatedMultipolygon.Create(IPath path, MemoryAllocator memoryAllocator)
   at SixLabors.ImageSharp.Drawing.Shapes.Rasterization.PolygonScanner.Create(IPath polygon, Int32 minY, Int32 maxY, Int32 subsampling, IntersectionRule intersectionRule, MemoryAllocator allocator)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.CachingGlyphRenderer.Render(IPath path)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.CachingGlyphRenderer.EndGlyph()
   at SixLabors.Fonts.GlyphMetrics.RenderTo(IGlyphRenderer surface, Single pointSize, Vector2 location, TextOptions options)
   at SixLabors.Fonts.TextRenderer.RenderText(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextRenderer.RenderText(String text, TextOptions options)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.BeforeImageApply()
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, DrawingOptions drawingOptions, String text, Font font, IBrush brush, IPen pen, PointF location)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, DrawingOptions drawingOptions, String text, Font font, Color color, PointF location)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, String text, Font font, Color color, PointF location)
   at ConsoleApp.Program.<>c__DisplayClass0_1.<Main>b__0(IImageProcessingContext x) in D:\Programming\C#\Console\Program.cs:line 48
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.ProcessingVisitor.Visit[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Image`1.Accept(IImageVisitor visitor)
   at SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.AcceptVisitor(Image source, IImageVisitor visitor)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate(Image source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate(Image source, Action`1 operation)
   at ConsoleApp.Program.Main(String[] args) in D:\Programming\C#\Console\Program.cs:line 48
```

It depends on image size I guess but in my example all of allocations are quite small so they go to `ArrayPool<T>` which never releases its buffers thus memory won't go lower than the most stress scenario level.

**Comment by br3aker** [comment]
Please do not close this before issue I've linked from `ImageSharp.Drawing` is closed. Better to be 100% sure mentionted leak is the only one.
