### ISSUE TITLE
image sharper throws invalidimagecontentexception

### ISSUE THREAD

**Issue by vindhya124** [SixLabors/ImageSharp#2159]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.0.0.0

### Other ImageSharp packages and versions

2

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

4.7.2

### Description

image sharper throws invalidimagecontentexception when i upload below images from Huawei phone.

Below is the error details.
at SixLabors.ImageSharp.Formats.Jpeg.JpegThrowHelper.ThrowInvalidImageContentException(String errorMessage)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ProcessApplicationHeaderMarker(BufferedReadStream stream, Int32 remaining)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ParseStream(BufferedReadStream stream, HuffmanScanDecoder scanDecoder, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass130_0`1.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Byte[] data)
   at Givealittle.Domain.Assets.AssetProcessing.ScaleImage(ILogger logger, Byte[] source, Int32 width, IImageEncoder encoder) in C:\Development\GivealittleV4\Src\Givealittle.Domain\Assets\AssetProcessing.cs:line 114

### Steps to Reproduce

image sharper throws invalidimagecontentexception when i upload below images from Huawei phone.

### Images

![Uploading fa0c158e-1c82-40fb-808e-aea100dbfeeb.jpg…]()

**Comment by br3aker** [comment]
Reupload the image please, you have a corrupted link.

**Comment by vindhya124** [comment]
Below is the image.

![fa0c158e-1c82-40fb-808e-aea100dbfeeb](https://user-images.githubusercontent.com/38023844/174543954-32856074-eb03-4333-b5ba-b34b24a2f44e.jpg)

**Comment by br3aker** [comment]
Can't reproduce it. Most likely it was fixed in some of the `2.1.X` versions, [can you check newest 2.1.3 version](https://github.com/SixLabors/ImageSharp/releases/tag/v2.1.3)?

**Comment by JimBobSquarePants** [comment]
>I have verified that I am running the latest version of ImageSharp

**Comment by vindhya124** [comment]
> Can't reproduce it. Most likely it was fixed in one of the `2.1.X` versions, [can you check newest 2.1.3 version](https://github.com/SixLabors/ImageSharp/releases/tag/v2.1.3)?

It worked with the latest version. Thank you mate.

**Comment by vindhya124** [comment]
> > I have verified that I am running the latest version of ImageSharp
> 
> It helps us when these questions are answered accurately.
Visual studio is showing 2.1.0 as the latest version.
