### ISSUE TITLE
ImageSharp can't load Photoshop webp images

### ISSUE THREAD

**Issue by BowserKingKoopa** [SixLabors/ImageSharp#2243]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.0-alpha.0.52

### Other ImageSharp packages and versions

n/a

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

6

### Description

ImageSharp throws an Exception when trying to load a webp image saved from the latest version of Photoshop (23.5.1). The exception is "Unexpected chunk followed VP8X header".

### Steps to Reproduce

Open the attached png file in photoshop. Save A Copy with default options (Lossy, Quality: 75%).  Try to load the image with ImageSharp (Image.Load("myimage.webp")) and you'll get an "Unexpected chunk followed VP8X header". (I'd attached the webp image as well but GitHub says it doesn't support webp). 

### Images

![bahama-breeze](https://user-images.githubusercontent.com/11095411/192416122-896d6ff5-809b-4446-8229-6cca367e1806.png)

**Comment by JimBobSquarePants** [comment]
Stick the image in a zip file. We can’t do much without it.

**Comment by BowserKingKoopa** [comment]
[photoshop-webp.zip](https://github.com/SixLabors/ImageSharp/files/9651573/photoshop-webp.zip)

The webp image zipped and attached, saved from the latest version of Photoshop with default settings.

**Comment by brianpopow** [comment]
output from webpinfo:
````
RIFF HEADER:
  File size:  55068
Chunk VP8X at offset     12, length     18
  ICCP: 1
  Alpha: 0
  EXIF: 0
  XMP: 0
  Animation: 0
  Canvas size 4000 x 4000
Chunk ICCP at offset     30, length   3152
Chunk VP8  at offset   3182, length  51800
  Width: 4000
  Height: 4000
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
Warning: Unknown chunk at offset  54982, length     86
No error detected.
There were 1 warning(s).
````

**Comment by brianpopow** [comment]
Yes we can skip this, should be an easy fix (if the length is correct)

**Comment by kmai-universe** [comment]
Hi, i'm using ImageSharp through Umbraco and can verify that i'm using the latest version of imagesharp. I still get this error with images saved as webP from Adobe Photoshop.

SixLabors.ImageSharp 2.1.3
SixLabors.ImageSharp.Web 2.0.2

Error:
`SixLabors.ImageSharp.ImageFormatException: Unexpected chunk followed VP8X header
   at SixLabors.ImageSharp.Formats.Webp.WebpThrowHelper.ThrowImageFormatException(String errorMessage)
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoderCore.ReadVp8XHeader()
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoderCore.ReadVp8Info()
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoder.Decode[TPixel](Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoder.Decode(Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass131_0.<LoadWithFormatAsync>b__0(Stream s, CancellationToken ct)
   at SixLabors.ImageSharp.Image.WithSeekableStreamAsync[T](Configuration configuration, Stream stream, Func`3 action, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.LoadWithFormatAsync(Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Web.FormattedImage.LoadAsync(Configuration configuration, Stream source)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext httpContext, IImageResolver sourceImageResolver, ImageContext imageContext, CommandCollection commands, Boolean retry)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext httpContext, IImageResolver sourceImageResolver, ImageContext imageContext, CommandCollection commands, Boolean retry)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()`

**Comment by JimBobSquarePants** [comment]
If you read this thread you will see that the issue is fixed for release for the upcoming v3 release.

**Comment by kmai-universe** [comment]
> If you read this thread you will see that the issue is fixed for release for the upcoming v3 release.

Hi, yes you're right! Must have been too early in the morning for me. Thanks for the heads up.

**Comment by JimBobSquarePants** [comment]
No worries. Happens to the best of us! 😄
