### ISSUE TITLE
ImageSource.FromBinary throws MethodNotFoundException

### ISSUE THREAD

**Issue by sparkybg** [SixLabors/ImageSharp#2441]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

3.0.0

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

6.0

### Description

Code:

 
>public void PrintImage(string fileName, byte[] content, double x, double y, double w, double h)
>{        
>    var imgSrc = ImageSource.FromBinary(fileName, () => content, 100); //throws here
>    ...
>}

The file loaded in the byte buffer is JPG. It throws exception on any JPG. I did not try other formats.

The problem is not present in version 2.1.4.

From what I found in the net, there was a similar problem when migrating from version 2.0 to 2.1, but I cannot confirm this myself.

Exception details:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(Byte[], SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.
  Source=PdfSharpCore
  StackTrace:
   at PdfSharpCore.Utils.ImageSharpImageSource`1.FromBinaryImpl(String name, Func`1 imageSource, Nullable`1 quality)
   at OTLive.Web.Infrastructure.Ls.PdfPrint.PrintImage(String fileName, Byte[] content, Double x, Double y, Double w, Double h) in C:\Prog\Team\Dev\OTLive-Dev\OTLive.Web\Infrastructure\Ls\PdfPrint.cs:line 123
   at OTLive.Web.Infrastructure.Ls.Document.PrintDocument() in C:\Prog\Team\Dev\OTLive-Dev\OTLive.Web\Infrastructure\Ls\Document.cs:line 1756
   at OTLive.Web.Infrastructure.Ls.Document.Print(OTLiveWorksession WS, Int32 documentID, String Type) in C:\Prog\Team\Dev\OTLive-Dev\OTLive.Web\Infrastructure\Ls\Document.cs:line 471
   at OTLive.Web.Controllers.Ls.Main.DokumentiController.PrintDocument(Int32 id, String file, String fileName) in C:\Prog\Team\Dev\OTLive-Dev\OTLive.Web\Controllers\WebAPI\Ls\Main\DokumentiController.cs:line 179
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

### Steps to Reproduce

1. Load JPG image in byte buffer.
2. Call ImageSource.FromBinary method

Alternate

1. Create MomeryStream from loaded image or filestream to JPG file.
2. Call XImage.FromStream method.

**Comment by JimBobSquarePants** [comment]
This is not an ImageSharp issue.

Whatever codebase that contains `ImageSource.FromBinary` needs to be recompiled against ImageSharp v3 because the new major version contains binary breaking changes.

**Comment by sparkybg** [comment]
When I install 2.1.4 nuget package in my VS2022 project, it works. When I update package to 3.0.0 or 3.1.0, it does not. I am recompiling every time - it is a VS2022 project I am working on.
