### ISSUE TITLE
Drawing part of an image onto another image throws ImageProcessingException or ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Visual-Vincent** [SixLabors/ImageSharp#2447]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1, 3.0.2-alpha.0.15

### Other ImageSharp packages and versions

(None)

### Environment (Operating system, version and so on)

Windows 7 SP1 x64, Windows 11 21H2 x64

### .NET Framework version

.NET 6.0

### Description

The `DrawImage(Image, Point, Rectangle, float)` method was added in 3.0.0 after #2112 and #2102 requested a method which could draw part of one image onto another. However, the method does not seem to work as intended as more often than not it throws one of two exceptions, or simply fails to produce the correct image.

### Steps to Reproduce

The following code tries to draw a 32 x 32 piece of a 512 x 512 image onto a 100 x 100 image.

<details>
<summary>ImageProcessingException</summary>

```csharp
using var src = Image.Load<Rgba32>("numbergrid.png");
using var dst = new Image<Rgba32>(100, 100, new Rgba32(0, 255, 255));

dst.Mutate(c => {
    c.DrawImage(src, new Point(64, 10), new Rectangle(32, 32, 32, 32), 1.0f);
});

dst.SaveAsPng("result.png");
```

Expected result:

![Expected result](https://user-images.githubusercontent.com/12941377/236338955-af558e25-d3a8-462c-bf55-9186731ef4bf.png)

Exception:

```
SixLabors.ImageSharp.ImageProcessingException
  HResult=0x80131500
  Message=Cannot draw image because the source image does not overlap the target image.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Processing.Processors.Drawing.DrawImageProcessor`2.OnFrameApply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DrawImageExtensions.DrawImage(IImageProcessingContext source, Image image, Point location, Rectangle rectangle, PixelColorBlendingMode colorBlending, PixelAlphaCompositionMode alphaComposition, Single opacity)
   at SixLabors.ImageSharp.Processing.DrawImageExtensions.DrawImage(IImageProcessingContext source, Image image, Point location, Rectangle rectangle, Single opacity)
   at ImageSharp_DrawImage_SrcRect_Test.Form1.<>c__DisplayClass2_0.<Form1_Shown>b__0(IImageProcessingContext c) in [REDACTED]
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)

   (...continues with my application's stack trace...)
```

</details>

<details>
<summary>ArgumentOutOfRangeException</summary>

```csharp
using var src = Image.Load<Rgba32>("numbergrid.png");
using var dst = new Image<Rgba32>(100, 100, new Rgba32(0, 255, 255));

dst.Mutate(c => {
    c.DrawImage(src, new Point(10, 10), new Rectangle(320, 128, 32, 32), 1.0f);
});

dst.SaveAsPng("result.png");
```

Expected result:

![Expected result](https://user-images.githubusercontent.com/12941377/236339125-4aecc76d-382e-406a-88e4-b8fb5f4e6b5e.png)

Exception:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values. Arg_ParamName_Name
  Source=SixLabors.ImageSharp
  ParamName=DangerousGetRowSpan(128). Y was out of range. Height=100
  StackTrace:
   at SixLabors.ImageSharp.Memory.Buffer2D`1.ThrowYOutOfRangeException(Int32 y)
   at SixLabors.ImageSharp.Memory.Buffer2D`1.DangerousGetRowSpan(Int32 y)
   at SixLabors.ImageSharp.Processing.Processors.Drawing.DrawImageProcessor`2.RowOperation.Invoke(Int32 y)
   at SixLabors.ImageSharp.Advanced.ParallelRowIterator.IterateRows[T](Rectangle rectangle, ParallelExecutionSettings& parallelSettings, T& operation)
   at SixLabors.ImageSharp.Advanced.ParallelRowIterator.IterateRows[T](Configuration configuration, Rectangle rectangle, T& operation)
   at SixLabors.ImageSharp.Processing.Processors.Drawing.DrawImageProcessor`2.OnFrameApply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DrawImageExtensions.DrawImage(IImageProcessingContext source, Image image, Point location, Rectangle rectangle, PixelColorBlendingMode colorBlending, PixelAlphaCompositionMode alphaComposition, Single opacity)
   at SixLabors.ImageSharp.Processing.DrawImageExtensions.DrawImage(IImageProcessingContext source, Image image, Point location, Rectangle rectangle, Single opacity)
   at ImageSharp_DrawImage_SrcRect_Test.Form1.<>c__DisplayClass2_0.<Form1_Shown>b__0(IImageProcessingContext c) in [REDACTED]
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)

   (...continues with my application's stack trace...)
```

</details>

<details>
<summary>No exception, but incorrect result</summary>

```csharp
using var src = Image.Load<Rgba32>("numbergrid.png");
using var dst = new Image<Rgba32>(100, 100, new Rgba32(0, 255, 255));

dst.Mutate(c => {
    c.DrawImage(src, new Point(10, 10), new Rectangle(32, 32, 32, 32), 1.0f);
});

dst.SaveAsPng("result.png");
```

Expected result:

![Expected result](https://user-images.githubusercontent.com/12941377/236338077-dce0a485-fd28-43b8-9a7d-b95cedafaa80.png)

Actual result:

![Actual result](https://user-images.githubusercontent.com/12941377/236338214-7d09d6ef-f0b9-464a-b129-874f816e802f.png)

</details>

<details>
<summary>Alternative code that produces the correct result</summary>

The following code clones and crops the source image instead, which produces the expected result regardless of the coordinates used:

```csharp
using var src = Image.Load<Rgba32>("numbergrid.png");
using var dst = new Image<Rgba32>(100, 100, new Rgba32(0, 255, 255));

dst.Mutate(c => {
    using var slice = src.Clone(c => c.Crop(new Rectangle(32, 32, 32, 32)));
    c.DrawImage(slice, new Point(10, 10), 1.0f);
});
```

Result:

![Correct result](https://user-images.githubusercontent.com/12941377/236340418-00df66c8-1ca1-4b88-8028-c2c219f96cdc.png)

Since this does unnecessary cloning and cropping of the source image, this is not a viable option.

</details>

### Images

The image `numbergrid.png` used in the code:

![numbergrid.png](https://user-images.githubusercontent.com/12941377/236339389-e1f94ea5-cacd-4c87-945c-0866b6214954.png)

**Comment by JimBobSquarePants** [comment]
Thanks for raising such a detailed issue! 😍

There's definitely issues here and I'll have a look at fixing them using your examples as a test asap.

**Comment by Visual-Vincent** [comment]
Thank you. Feel free to use these images for anything you may need them to, including unit tests.

I look forward to see what you discover!

**Comment by JimBobSquarePants** [comment]
I've opened a PR for this now. Thanks again for providing such detail. It enabled me to write a bunch of tests much more easily! 👍
