### ISSUE TITLE
Jpeg compressed tiff with photometric interpretation Separated is not supported

### ISSUE THREAD

**Issue by shapeh** [SixLabors/ImageSharp#2454]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 11 and Windows Server 2022

### .NET Framework version

.NET 7.0.5

### Description

Hi, 

I am getting this error when trying to resize a tiff image:

**Jpeg compressed tiff with photometric interpretation Separated is not supported**

I looked at this: https://github.com/SixLabors/ImageSharp/issues/12 and maybe it is still relevant, despite edited 2021? 
_"Photometric Interpretation Formats:  Separated (TIFF Extension color spaces)" - not ticked._
Update: https://github.com/SixLabors/ImageSharp/blob/main/src/ImageSharp/Formats/Tiff/README.md - Separated seems to be supported?

Is there a plan for support at a later stage?

Thanks for a great library.

> System.Exception: System.NotSupportedException: Jpeg compressed tiff with photometric interpretation Separated is not supported
>    at SixLabors.ImageSharp.Formats.Tiff.TiffThrowHelper.ThrowNotSupported(String message)
>    at SixLabors.ImageSharp.Formats.Tiff.Compression.Decompressors.JpegTiffCompression.DecodeJpegData(BufferedReadStream stream, Span`1 buffer, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.Compression.Decompressors.JpegTiffCompression.Decompress(BufferedReadStream stream, Int32 byteCount, Int32 stripHeight, Span`1 buffer, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.Compression.TiffBaseDecompressor.Decompress(BufferedReadStream stream, UInt64 stripOffset, UInt64 stripByteCount, Int32 stripHeight, Span`1 buffer, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeStripsChunky[TPixel](ImageFrame`1 frame, Int32 rowsPerStrip, Span`1 stripOffsets, Span`1 stripByteCounts, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeImageWithStrips[TPixel](ExifProfile tags, ImageFrame`1 frame, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeFrame[TPixel](ExifProfile tags, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode[TPixel](DecoderOptions options, Stream stream, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.ImageDecoder.<>c__DisplayClass12_0`1.<WithSeekableMemoryStreamAsync>g__PeformActionAndResetPosition|0(Stream s, Int64 position, CancellationToken ct)
> --- End of stack trace from previous location ---
>    at SixLabors.ImageSharp.Formats.ImageDecoder.CopyToMemoryStreamAndActionAsync[T](DecoderOptions options, Stream stream, Func`4 action, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Formats.ImageDecoder.DecodeAsync(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
>    at SixLabors.ImageSharp.Image.WithSeekableStreamAsync[T](DecoderOptions options, Stream stream, Func`3 action, CancellationToken cancellationToken)

### Steps to Reproduce

The code is simple like this (image is coming from Azure Blob Storage but that is not the issue):

```
   ...
   ushort width = 600;
   var azureBlobData = await blob.OpenReadAsync(null, cancellationToken: token); // blob holds reference to the affected tiff image.
   using var image = await Image.LoadAsync(azureBlobData, token);
            var typeOfImage = image.Metadata.DecodedImageFormat; // for use later on.

            // resize original image to new width:
            image.Mutate(x =>
                x.AutoOrient()
                .Resize(width, 0)
            ); 
  ....
```

### Images

[LC-Snow_Snow.zip](https://github.com/SixLabors/ImageSharp/files/11464090/LC-Snow_Snow.zip)
[Aeros.zip](https://github.com/SixLabors/ImageSharp/files/11566357/Aeros.zip)

**Comment by brianpopow** [comment]
We actually support photometric interpretation Separated, see [CmykTests](https://github.com/SixLabors/ImageSharp/blob/b11f4db1e98b014e1f83858d77bb7ec432cf5268/tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs#L312).

The issue here comes from the combination of JPEG compression and separated. I am not sure how to decode those image, that's why it's disabled and throws an exception with that message.

If I map the colorspace for separated to CMYK in `TiffJpegSpectralConverter.cs` the image does not look correct:
![output](https://github.com/SixLabors/ImageSharp/assets/38701097/3dfaed65-d8be-48a5-a1e8-ccc71f27688a)

You can help figuring out what needs  to be done to decode this image. Even better would be to provide a PR with a fix, but figuring out what needs to be done to decode this would already be very helpful.

**Comment by shapeh** [comment]
I am no expert in image formats and their underlying algorithms. I did some digging (not sure if it is helpful or you are already aware of this): 

From the file:
```
<dc:format>image/tiff</dc:format>
<photoshop:ColorMode>4</photoshop:ColorMode>
<photoshop:ICCProfile>Generic CMYK</photoshop:ICCProfile>
<tiff:BitsPerSample>
<rdf:Seq>
   <rdf:li>8</rdf:li>
   <rdf:li>8</rdf:li>
   <rdf:li>8</rdf:li>
   <rdf:li>8</rdf:li>
</rdf:Seq>
</tiff:BitsPerSample>
<tiff:Compression>7</tiff:Compression>
<tiff:PhotometricInterpretation>5</tiff:PhotometricInterpretation>
<tiff:Orientation>1</tiff:Orientation>
<tiff:SamplesPerPixel>4</tiff:SamplesPerPixel>
<tiff:PlanarConfiguration>1</tiff:PlanarConfiguration>
```

So 7, JPEG Compression (new format), PhotometricInterpretation 5 equals CMYK. 

From https://www.kronometric.org/phot/processing/DNG/dng_spec_1.4.0.0.pdf p. 19:

> Two Compression tag values are supported in DNG versions before 1.4.0.0:
> - Value = 1: Uncompressed data.
> - Value = 7: JPEG compressed data, either baseline DCT JPEG, or lossless JPEG 
> compression.
> 
> If PhotometricInterpretation = 6 (YCbCr) and BitsPerSample = 8/8/8, or if 
> PhotometricInterpretation = 1 (BlackIsZero) and BitsPerSample = 8, then the JPEG variant 
> must be baseline DCT JPEG.
> 
> Otherwise, the **JPEG variant must be lossless Huffman JPEG**. For lossless JPEG, the internal 
> width/length/components in the JPEG stream are not required to match the strip or tile's 
> width/length/components. Only the total sample counts need to match. It is common for CFA 
> images to be encoded with a different width, length or component count to allow the JPEG 
> compression predictors to work across like colors.

So, I guess we are looking at 'a lossless Huffman JPEG'? 
Perhaps some code like this: 
https://github.com/yigolden/JpegLibrary => https://github.com/yigolden/JpegLibrary/blob/main/src/JpegLibrary/ScanDecoder/JpegHuffmanLosslessScanDecoder.cs

Is this helpful (or am I out of my depth)?

**Comment by shapeh** [comment]
Here are the images converted to jpgs in Photoshop:

![LC-Snow_Snow](https://github.com/SixLabors/ImageSharp/assets/29387615/a1e70666-6f6f-4b9a-a233-7f2eed295522)
![Aeros](https://github.com/SixLabors/ImageSharp/assets/29387615/507881c4-7363-4f8d-81ca-ac4e79c96f2b)

**Comment by shapeh** [comment]
@brianpopow -  I am glad it is helpful. 

I looks like the decompression works (because you can identify some of artifacts (window frame, funky chair etc) in your conversion that resembles the correct image).

Re no. 2 - Okay with the conversion to RGB from CMYK. 
Is this necessary because JPEG does not support CMYK or does it have something to do with the internals of ImageSharp?

Please let me know if there is anything I can help with/investigate further.

**Comment by JimBobSquarePants** [comment]
@brianpopow TiffLibrary seems to have this covered. Is this useful to you?

https://github.com/yigolden/TiffLibrary/blob/cec3a858de270a74965abe5b57a19b12c7a0e8d0/src/TiffLibrary/ImageDecoder/TiffD
efaultImageDecoderFactory.cs#L735-L742

**Comment by JimBobSquarePants** [comment]
Thanks for looking into this @brianpopow 

Is it really Rgba?

It does seem that there are rgba jpegs out there.

https://stackoverflow.com/questions/6212897/can-i-use-libjpeg-to-read-jpegs-with-an-alpha-channel

Are you absolutely sure that the test CMYK image is the same as the sample? I was able to open the CMYK image with Windows Photo Viewer and Paint.NET but not LC-Snow_snow

**Comment by brianpopow** [comment]
> It does seem that there are rgba jpegs out there.
> 
> https://stackoverflow.com/questions/6212897/can-i-use-libjpeg-to-read-jpegs-with-an-alpha-channel

I was not able to get those jpeg files from the stackoverflow post. The links seem to be broken.

> 
> Are you absolutely sure that the test CMYK image is the same as the sample? I was able to open the CMYK image with Windows Photo Viewer and Paint.NET but not LC-Snow_snow

Both images have Compression Scheme: JPEG and Photometric Interpretation: separated, so I thought they should be similar enough. The CMYK image has not color profile and only 4 colors, so I thought it would make debugging easier.
It was created with imagemagick: magick `Cmyk.tiff -compress jpeg Cmyk.test.jpg`
The input image is `Cmyk.tiff` from our test file directory. Not sure why some viewers have trouble with LC-Snow image. I noticed some warnings from tiffinfo:
```
TIFFReadDirectory: Warning, Unknown field with tag 347 (0x15b) encountered.
TIFFFetchNormalTag: Warning, Incorrect value for "RichTIFFIPTC"; tag ignored.
```
Other then that I am not sure what the problem is.

The only viewer I found which can display the LC-Snow image correctly is XnView:
![LC-Snow_Snow](https://github.com/SixLabors/ImageSharp/assets/38701097/881b92fd-9e32-4abf-8068-a1036da00671)

**Comment by shapeh** [comment]
> The only viewer I found which can display the LC-Snow image correctly is XnView (besides photoshop, which the OP has mentioned can open the files correctly):

Just a minor comment: I think this image from XnView is showing some weird greens/blues - it looks different from the image from Photoshop, i.e. less warm color tones.

**Comment by shapeh** [comment]
Here is the same image opened in Windows 11 Paint. Colors off but still opens.

<img width="873" alt="paint-win11" src="https://github.com/SixLabors/ImageSharp/assets/29387615/37a527e4-da11-4ff1-8256-eb6167b33a1f">

**Comment by JimBobSquarePants** [comment]
All my hack does (I think) is trick the decoder into actually doing something which allows following decoders to read the color space type. I think we should try your plan but maybe with a different name for the colorspace, Rgba seems inaccurate.

**Comment by JimBobSquarePants** [comment]
Well done making progress on this! 

>So the color conversion is done on the jpeg side not tiff. I would have preferred it to be handled by the tiff side

I was actually surprised it was done in the Tiff side. I always assumed it was supposed to happen in jpeg/gif etc...

Regarding identification. My guess is that there is actually additional AppN markers in the jpeg stream (App14) that would allow us to identify that the image is encoded using YccK color. The below link states that those markers found in the stream should be ignored though. If we open the file in the same manner as almost everything else, I think we should just stick with that for now.

https://web.archive.org/web/20210108174708/https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFFphotoshop.pdf

P.S. While I was searching for answers this seemed relevant. 
https://github.com/ImageMagick/ImageMagick/issues/6094

**Comment by JimBobSquarePants** [comment]
@brianpopow Do you have your code stub for this online?

**Comment by brianpopow** [comment]
I have started to work on this in the branch `bp/tiff-jpeg-cmyk`, this can decode a jpeg with cmyk (see the test `TiffDecoder_CanDecode_Cmyk`),
but I was not yet able to figure out what needs to be done to decode the image correctly provide here in this issue.

**Comment by JimBobSquarePants** [comment]
Thanks. So, we do the same as MS Paint now. I'll have a read through to see if there is anything I can find.

![TiffDecoder_CanDecode_Cmyk_Rgba32_issue2454-A](https://github.com/SixLabors/ImageSharp/assets/385879/407fb5cc-5994-4d57-b005-3ee293a5105f)

**Comment by juliusdeblaaij** [comment]
Hi all, I'm checking about using tiff.
So in the current state, is there a stable way to convert JPEG files to a multi-page tiff? If so, can someone provide pseudo code?
The reason I ask is because there seem to be complex issues with JPEG and tiff in this thread.
Assume I'm talking about JPEG files taken from s phone camera, i assume those are RGB?

Thanks for any info!

**Comment by juliusdeblaaij** [comment]
> This thread is about decoding specific tiff files using joeg compression that do not appear to work outside of photoshop. Encoding multiframe tiff files is entirely supported.

Pfew! Thanks.

**Comment by JimBobSquarePants** [comment]
OK.... Time to look at this again. 

@shapeh The images you provided appear to be YccK not Cmyk. If we can figure out how to correctly detect the difference, then I'm certain we can display them properly one I wire up the ICC profile conversion. Using forced YccK input they look like this. 

![Image](https://github.com/user-attachments/assets/e08d23e0-9461-466e-b159-ed0077bd1e59)

 Update. The color space is in the raw JpegData. I can get it from there. We don't need the interpretation.

**Comment by shapeh** [comment]
@JimBobSquarePants thanks for the continued effort.  The forced YccK gives off a cold color tone in the samples you provided but perhaps that is because of the ICC profile?

Perhaps the images are just saved wrongly whenever they were created, or?

i.e. it is not _"JPEG Compression (new format), PhotometricInterpretation 5 equals CMYK."_

 
```

<dc:format>image/tiff</dc:format>
<photoshop:ColorMode>4</photoshop:ColorMode>
<photoshop:ICCProfile>Generic CMYK</photoshop:ICCProfile>
<tiff:BitsPerSample>
<rdf:Seq>
   <rdf:li>8</rdf:li>
   <rdf:li>8</rdf:li>
   <rdf:li>8</rdf:li>
   <rdf:li>8</rdf:li>
</rdf:Seq>
</tiff:BitsPerSample>
<tiff:Compression>7</tiff:Compression>
<tiff:PhotometricInterpretation>5</tiff:PhotometricInterpretation>
<tiff:Orientation>1</tiff:Orientation>
<tiff:SamplesPerPixel>4</tiff:SamplesPerPixel>
<tiff:PlanarConfiguration>1</tiff:PlanarConfiguration>


```

**Comment by JimBobSquarePants** [comment]
@shapeh The tonal difference will be because we're not using ICC profile to convert colors. Once I wire up the converter to use the profile I think we should get an almost exact match to the Photoshop output. 

YCCK is not a defined ICC color space — it's a JPEG-specific encoding used in Adobe-style CMYK JPEGs. These TIFF files are basically wrappers around JPEG information which correctly detects that the color is encoded as YCCK not CMYK. We need to take that into consideration, something it seems many decoders do incorrectly.

**Comment by JimBobSquarePants** [comment]
@shapeh That's the properly decoded image on the left using the ICC profile. Note the lack of over saturation.

![Image](https://github.com/user-attachments/assets/8d4e068c-526e-4b24-be49-b169c4a75d9f)

I have a lot of cleanup to do but I think we can safely say I'm on the right track. 

CC @brianpopow

**Comment by shapeh** [comment]
@JimBobSquarePants - nice! Yes, definitely - it seems like you have finally found the solution. Image on left is spot on.
Thanks for the explanation on YCCK/ICC, and a great library.
