### ISSUE TITLE
Input stream does not have enough bytes to parse declared contents of the 8D marker.

### ISSUE THREAD

**Issue by rajmondburgaj** [SixLabors/ImageSharp#2460]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.4

### Other ImageSharp packages and versions

2.1.4

### Environment (Operating system, version and so on)

Windows 11, Server 2016

### .NET Framework version

4.7.2

### Description

I am having this issue when I try to read the bytes from SQL Server and try to optimize/store the image in file system.

I am trying to understand what this error means in practice. All images are valid images from what I am aware, hence I am not sure if this indicates that the image is corrupted in any way or something else.

Below is the stacktrace:

```
   at SixLabors.ImageSharp.Formats.Jpeg.JpegThrowHelper.ThrowNotEnoughBytesForMarker(Byte marker)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ParseStream(BufferedReadStream stream, HuffmanScanDecoder scanDecoder, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode(Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass134_0.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Stream stream)
   at Sealogical.Services.Services.DocumentProcessor.Add(Guid id, DocumentGvResult document) in C:\Projects\Sealogical.Mvc\Sealogical.Services\Services\DocumentProcessor.cs:line 78
   at Sealogical.Services.Events.Handler.DocumentChangeEventHandler.<HandleAsync>d__3.MoveNext() in C:\Projects\Sealogical.Mvc\Sealogical.Services\Events\Handler\DocumentChangeEventHandler.cs:line 35
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sealogical.Services.Jobs.EventSourceJob.<HandleAsync>d__5`1.MoveNext() in C:\Projects\Sealogical.Mvc\Sealogical.Services\Jobs\EventSourceJob.cs:line 100
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sealogical.Services.Jobs.EventSourceJob.<Execute>d__4.MoveNext() in C:\Projects\Sealogical.Mvc\Sealogical.Services\Jobs\EventSourceJob.cs:line 51

```

Below is the code:

```c#
using (var memoryStream = new MemoryStream(document.Blob))
{
    memoryStream.Seek(0, SeekOrigin.Begin);

    using (var image = Image.Load(memoryStream))
    {
        int width = image.Height > 450 ? 450 : image.Width;
        image.Mutate(x => x.Resize(width, 0));
        image.Save(fullPath);
    }
}
```

### Steps to Reproduce

It's hard to reproduce because I am not sure what is the condition why this fails, maybe stack trace can help a bit.

The issue happens locally as well as in production, hence it happens on debug and release mode as well.

**Comment by JimBobSquarePants** [comment]
@rajmondburgaj Did you do the additional debugging required here? I'll have to close the issue otherwise as we do not have enough information to continue.

**Comment by rajmondburgaj** [comment]
Hi, the reason why it was not the latest is that I think the latest version was not compatible with the .net framework. Anyway, there was not much interest to follow up this issue on our side, hence we stopped the investigation why it happens, hence closing the issue.
