### ISSUE TITLE
Failed to load the tiff image

### ISSUE THREAD

**Issue by premkris1988** [SixLabors/ImageSharp#2490]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

windows 11

### .NET Framework version

.net 5

### Description

Some tiff images are giving this error while trying to load them.

"Message": "**Index was outside the bounds of the array.**",
      "Source": "SixLabors.ImageSharp",
      "StackTrace": "   at SixLabors.ImageSharp.Formats.Tiff.Compression.Decompressors.LzwString.WriteTo(Span`1 buffer, Int32 offset)
   at SixLabors.ImageSharp.Formats.Tiff.Compression.Decompressors.TiffLzwDecoder.DecodePixels(Span`1 pixels)
   at SixLabors.ImageSharp.Formats.Tiff.Compression.Decompressors.LzwTiffCompression.Decompress(BufferedReadStream stream, Int32 byteCount, Int32 stripHeight, Span`1 buffer, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeStripsChunky[TPixel](ImageFrame`1 frame, Int32 rowsPerStrip, Span`1 stripOffsets, Span`1 stripByteCounts, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeImageWithStrips[TPixel](ExifProfile tags, ImageFrame`1 frame, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeFrame[TPixel](ExifProfile tags, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode[TPixel](DecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoder.<>c__DisplayClass1_0.b__0(Stream s)
   at SixLabors.ImageSharp.Formats.ImageDecoder.g__PeformActionAndResetPosition|11_0[T](Stream s, Int64 position, <>c__DisplayClass11_0`1& )
   at SixLabors.ImageSharp.Formats.ImageDecoder.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Formats.ImageDecoder.Decode(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass80_0.b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.Load(Stream stream)
   
   have zipped and attached a sample image

### Steps to Reproduce

` var pngStream = new MemoryStream();
using (var image = SixLabors.ImageSharp.Image.Load(stream))
{
image.SaveAsPng(pngStream);
}
pngStream.Position = 0;
return (pngStream, "image/png");`

### Images

[not_loading_tiff.zip](https://github.com/SixLabors/ImageSharp/files/11934044/not_loading_tiff.zip)

**Comment by premkris1988** [comment]
@JimBobSquarePants could you please check this?

**Comment by JimBobSquarePants** [comment]
> @JimBobSquarePants could you please check this?

Do not tag me like this. The license for the project is clear and offers no guarantee of support. If you want an expedited result you should create a PR to fix the issue.

**Comment by premkris1988** [comment]
> > @JimBobSquarePants could you please check this?
> 
> Do not tag me like this. The license for the project is clear and offers no guarantee of support. If you want an expedited result you should create a PR to fix the issue.

Oh sorry for tagging you.
Was not aware of this.

**Comment by premkris1988** [comment]
Cloned the master branch to local and the problematic image is converted without an issue. Looks like the issue is already addressed. Will wait for the next release of the package. Closing the issue.

**Comment by JimBobSquarePants** [comment]
Good to know. Thanks for the update 👍

**Comment by premkris1988** [comment]
when can we expect the next release?

**Comment by JimBobSquarePants** [comment]
You are reaaaaaally not doing yourself any favors here. The answer is always. "When it's ready"

You can see the next milestone does not have a release date and still has 50% of the planned work to be reviewed and merged.

https://github.com/SixLabors/ImageSharp/milestone/12
