### ISSUE TITLE
CR2: System.NotSupportedException: Missing SOI marker offset for tiff with old jpeg compression

### ISSUE THREAD

**Issue by am11** [SixLabors/ImageSharp#2665]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.2

### Other ImageSharp packages and versions

-

### Environment (Operating system, version and so on)

Windows 11 amd64

### .NET Framework version

.NET 8.0

### Description

In a project, I have test assets with a CR2 image

[Berries.CR2.zip](https://github.com/SixLabors/ImageSharp/files/14276208/Berries.CR2.zip)

which windows file explorer preview for:

![image](https://github.com/SixLabors/ImageSharp/assets/3840695/60ebfdd1-81f5-4593-9213-f8120f89008a)

However, loading this image with ImageSharp fails:

```
      System.NotSupportedException: Missing SOI marker offset for tiff with old jpeg compression
         at SixLabors.ImageSharp.Formats.Tiff.TiffThrowHelper.ThrowNotSupported(String message)
         at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderOptionsParser.ParseCompression(TiffDecoderCore options, Nullable`1 compression, ExifProfile exifProfile)
         at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderOptionsParser.VerifyAndParse(TiffDecoderCore options, ExifProfile exifProfile, TiffFrameMetadata frameMetadata)
         at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeFrame[TPixel](ExifProfile tags, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode[TPixel](DecoderOptions options, Stream stream, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Formats.ImageDecoder.<>c__DisplayClass3_0.<DecodeAsync>b__0(Stream s, CancellationToken ct)
         at SixLabors.ImageSharp.Formats.ImageDecoder.<>c__DisplayClass12_0`1.<WithSeekableMemoryStreamAsync>g__PeformActionAndResetPosition|0(Stream s, Int64 position, CancellationToken ct)
      --- End of stack trace from previous location ---
         at SixLabors.ImageSharp.Formats.ImageDecoder.DecodeAsync(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
         at SixLabors.ImageSharp.Image.WithSeekableStreamAsync[T](DecoderOptions options, Stream stream, Func`3 action, CancellationToken cancellationToken)
```

I couldn't find much information whether or not Canon's CR2 support is deliberately left out. https://github.com/SixLabors/ImageSharp/blob/1f22bceef8bb79793cbdcc26ace38a726ad9b8c8/tests/Images/Input/Jpg/baseline/JpegSnoopReports/Lake.jpg.txt#L162 suggests it might not be intentional. Opening this issue just in case. :)

### Steps to Reproduce

```c#
using Image berries = await Image.LoadAsync(@"C:\temp\Berries.CR2");
```

**Comment by am11** [comment]
@JimBobSquarePants, thank you for the update. I think having the CR2 encoder/decoder (derived from TIFF?) would be a good fit for ImageSharp library. Compliance with standard, instead of Windows behavior, makes sense to me as well. File explorer example was just a reference point where this format is supported.
