### ISSUE TITLE
Image.Load() with System.ArgumentException "Not a valid pass index: 7"

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#313]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I try to load PNG image that displays normally. It also loads normally with .NET Framework's `System.Drawing.Image.FromFile()` and with ImageMagick.

### Steps to Reproduce

Simple code:
```
Image.Load("banner.png");
```
with image [banner_adam7.zip](https://github.com/SixLabors/ImageSharp/files/1255625/banner_adam7.zip) cause an `System.ArgumentException` with stacktrace:
```
   at ImageSharp.Formats.PngDecoderCore.ComputeColumnsAdam7(Int32 passIndex)
   at ImageSharp.Formats.PngDecoderCore.DecodeInterlacedPixelData[TPixel](Stream compressedStream, Image`1 image)
   at ImageSharp.Formats.PngDecoderCore.Decode[TPixel](Stream stream)
   at ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
   at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at ImageSharp.Image.Load(String path)
   at ImageSharpTest.Program.Main(String[] args) in C:\Users\user\Documents\Visual Studio 2017\Projects\ImageSharpTest\Program.cs:line 13
```

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00187
- Environment (Operating system, version and so on): Windows 10 Enterprise Version 1703 Build 15063.540
- Visual Studio Professional 2017 Version 15.3.2
- `dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by JimBobSquarePants** [comment]
Thanks! 

This will definitely be related to #301. I'm hoping someone can help out here as we've got a regressive issue I can't solve.

**Comment by JimBobSquarePants** [comment]
You're absolutely right to open this issue as they don't. I just mean that fixing that issue will most likely fix this one. (or vice versa)

**Comment by JimBobSquarePants** [comment]
Fixed!
