### ISSUE TITLE
Image.Load() with IndexOutOfRangeException "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#314]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I try to load 8-bit colormap interlaced PNG image that displays normally. It loads normally with .NET Framework's `System.Drawing.Image.FromFile()` and also with ImageMagick.
This bug could be related to #301.

### Steps to Reproduce

Simple code:
```
Image.Load("banner.png");
```
with image [banner_index.zip](https://github.com/SixLabors/ImageSharp/files/1256118/banner_index.zip) cause an `System.IndexOutOfRangeException` with stacktrace:
```
   at ImageSharp.Formats.PngDecoderCore.ProcessInterlacedDefilteredScanline[TPixel](Byte[] defilteredScanline, Span`1 rowSpan, Int32 pixelOffset, Int32 increment)
   at ImageSharp.Formats.PngDecoderCore.DecodeInterlacedPixelData[TPixel](Stream compressedStream, Image`1 image)
   at ImageSharp.Formats.PngDecoderCore.Decode[TPixel](Stream stream)
   at ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
   at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at ImageSharp.Image.Load(String path)
   at ImageSharpTest.Program.Main(String[] args) in C:\Users\user\Documents\Visual Studio 2017\Projects\ImageSharpTest\Program.cs:line 12
```

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00187
- Environment (Operating system, version and so on): Windows 10 Enterprise Version 1703 Build 15063.540
- Visual Studio Professional 2017 Version 15.3.2
- `dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by JimBobSquarePants** [comment]
Fixed!
