### ISSUE TITLE
Image.Load<Rgba32> Exception 'Bad RST marker'

### ISSUE THREAD

**Issue by cheesebar** [SixLabors/ImageSharp#416]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
SixLabors.ImageSharp.ImageFormatException: Bad RST marker
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.Components.Decoder.OrigJpegScanDecoder.DecodeBlocks(OrigJpegDecoderCore decoder)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.OrigJpegDecoderCore.ProcessStartOfScanMarker(Int32 remaining)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.OrigJpegDecoderCore.ParseStream(Stream stream, Boolean metadataOnly)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at CompressedImage.Program.CreateThumb(String image, String path, Nullable`1 dpi) in C:\work\project compressed image\code\CompressedImage\Program.cs:line 380

### System Configuration

- ImageSharp version:1.0.0 -beta0002
- Other ImageSharp packages and versions: 
SharpZipLib(1.0.0-alpha2)
SixLabors.ImageSharp.Drawing(1.0.0-beta0002)

- Environment (Operating system, version and so on): .net core
- .NET Framework version: .net core 2.0
- Additional information:

This JPG image is one of a number of photos I took with my mobile phone

**Comment by JimBobSquarePants** [comment]
Hi @cheesebar 

Can you please add the missing version information and also the image in question.

**Comment by cheesebar** [comment]
@JimBobSquarePants This JPG image is one of a number of photos I took with my mobile phone

**Comment by JimBobSquarePants** [comment]
@cheesebar Thanks for the additional information. Did the issue go away? 

If you don't fancy sharing an image publicly you can email me one and we can still try to work out the problem.
