### ISSUE TITLE
Resize => Unable to cast object of type 'SixLabors.ImageSharp.Primitives.Rational[]' to type 'SixLabors.ImageSharp.Primitives.Rational'

### ISSUE THREAD

**Issue by mabead** [SixLabors/ImageSharp#519]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Loading image and then trying to resize it and saving as jpeg throws exception.

### Steps to Reproduce
With 1.0.0-beta0003, calling the following code:

```
            using (var image = Image.Load(sourceStream))
            using (var outputFile = File.OpenWrite(target))
            {
                image.Mutate(ctx => ctx.Resize(newWidth, newHeight));
                image.SaveAsJpeg(outputFile);
            }
```

on this image [hikarinomachie.zip](https://github.com/SixLabors/ImageSharp/files/1892461/hikarinomachie.zip) results in this exception:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'SixLabors.ImageSharp.Primitives.Rational[]' to type 'SixLabors.ImageSharp.Primitives.Rational'.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifWriter.WriteValue(ExifDataType dataType, Object value, Byte[] destination, Int32 offset)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifWriter.WriteData(Collection`1 indexes, Byte[] destination, Int32 offset)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifWriter.GetData()
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.WriteExifProfile(ExifProfile exifProfile)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.WriteProfiles[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
```

### System Configuration

- ImageSharp version: 1.0.0-beta0003
- Environment: Windows
- .NET Framework version: dotnet core 2.0.5

**Comment by mabead** [comment]
Same for this file. 
[Axiom Federation square.zip](https://github.com/SixLabors/ImageSharp/files/1892465/Axiom.Federation.square.zip)

**Comment by JimBobSquarePants** [comment]
Issue template!
