### ISSUE TITLE
Image.Load throws TypeLoadException in Xamarin Android

### ISSUE THREAD

**Issue by Livven** [SixLabors/ImageSharp#657]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

```
System.TypeLoadException: Could not resolve type with token 0100007b (from typeref, class/assembly System.MemoryExtensions, System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) occurred
```

### Steps to Reproduce

- create new Xamarin Android project
- install SixLabors.ImageSharp package
- `Image.Load("foo.jpg")`
- bonus:
  - switch to release mode
  - project does not compile anymore with following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void SixLabors.ImageSharp.SimdUtils::BulkConvertNormalizedFloatToByte(System.ReadOnlySpan`1<System.Single>,System.Span`1<System.Byte>)' in assembly: 'SixLabors.ImageSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve !!0& System.Runtime.InteropServices.MemoryMarshal::GetReference(System.ReadOnlySpan`1<!!0>)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	App7			
```

### System Configuration

- ImageSharp version: 1.0.0-beta0004
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by iamcarbon** [comment]
This is an Xamarin bug -- are you able to raise the issue over there?
