### ISSUE TITLE
NullReferenceException when loading jpeg image

### ISSUE THREAD

**Issue by mabead** [SixLabors/ImageSharp#695]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Loading image throws exception.

### Steps to Reproduce
With 1.0.0-beta005, calling Image.Load on the attached file throws the following exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.SixLabors.ImageSharp.Formats.Jpeg.Components.Decoder.IRawJpegData.get_Components()
   at SixLabors.ImageSharp.Formats.Jpeg.Components.Decoder.JpegImagePostProcessor..ctor(MemoryAllocator memoryAllocator, IRawJpegData rawJpeg)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.PostProcessIntoImage[TPixel]()
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Stream stream)
   at LANDR.Distribution.ImageProcessor.PictureProvider.Resize(Stream sourceStream, String target, Int32 newWidth, Int32 newHeight) in C:\git\Distribution\src\LANDR.Distribution.ImageProcessor\PictureProvider.cs:line 81
```

Here's the file: 
[i think im in love art 3000pg.zip](https://github.com/SixLabors/ImageSharp/files/2357364/i.think.im.in.love.art.3000pg.zip)

### System Configuration

- ImageSharp version: 1.0.0-beta005
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): windows
- .NET Framework version: .NET core 2.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Fixed with #699
