### ISSUE TITLE
ImageProcessingException: An error occurred when processing the image using CropProcessor

### ISSUE THREAD

**Issue by Rody66** [SixLabors/ImageSharp#750]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Exception throws when I try to apply EntropyCrop method to this image:
https://yadi.sk/d/nU_mjlfkV5UI2w

Call Stack:
```
SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using EntropyCropProcessor`1. See the inner exception for more detail. ---> SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using CropProcessor`1. See the inner exception for more detail. ---> System.ArgumentNullException: Array cannot be null.
Parameter name: bytes
    at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount)
   at SixLabors.ImageSharp.EncoderExtensions.GetString(Encoding encoding, ReadOnlySpan`1 buffer)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifReader.ConvertToString(ReadOnlySpan`1 buffer)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifReader.ConvertValue(ExifDataType dataType, ReadOnlySpan`1 buffer, UInt32 numberOfComponents)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifReader.TryReadValue(ExifValue& exifValue)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifReader.AddValues(List`1 values, UInt32 index)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifReader.ReadValues()
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifProfile.InitializeValues()
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifProfile.GetValue(ExifTag tag)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.TransformHelpers.UpdateDimensionalMetData[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.TransformProcessorBase`1.AfterImageApply(Image`1 source, Image`1 destination, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.CloneAndApply(Image`1 source, Rectangle sourceRectangle)
--- End of inner exception stack trace ---
    at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.CloneAndApply(Image`1 source, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.Apply(Image`1 source, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.EntropyCropProcessor`1.BeforeImageApply(Image`1 source, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply(Image`1 source, Rectangle sourceRectangle)
--- End of inner exception stack trace ---
    at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply(Image`1 source, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.DefaultInternalImageProcessorContext`1.ApplyProcessor(IImageProcessor`1 processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultInternalImageProcessorContext`1.ApplyProcessor(IImageProcessor`1 processor)
   at SixLabors.ImageSharp.Processing.EntropyCropExtensions.EntropyCrop[TPixel](IImageProcessingContext`1 source, Single threshold)
```

### Steps to Reproduce
```csharp
            using (var image = Image.Load("img20.jpg"))
            {
                image.Mutate(x => x.EntropyCrop(0.07f));
            }
```

- ImageSharp version: 1.0.0-dev002072
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Win 10
- .NET Framework version: 4.6.2
- Additional information:
![img20](https://user-images.githubusercontent.com/36400912/47466029-0b861d00-d7f8-11e8-9853-886cbbce5273.JPG)

**Comment by JimBobSquarePants** [comment]
Looks like the EXIF metadata is somehow corrupted @dlemstra I'll need your help here.
