### ISSUE TITLE
Android linker error when linking SDK assemblies

### ISSUE THREAD

**Issue by dmanning23** [SixLabors/ImageSharp#752]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to use the latest ImageSharp nuget package (currently v1.0.0-alpha9-00194) in an Android project, the project doesnt build when the linker is set to "SDK Assemblies Only".
It throws the following error:
```
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'ImageSharp.Image`1<TPixel> ImageSharp.Image::LoadPixelData(ImageSharp.Configuration,System.Span`1<System.Byte>,System.Int32,System.Int32)' in assembly: 'ImageSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Span`1<!!1> System.SpanExtensions::NonPortableCast(System.Span`1<!!0>)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Testbed.Android		
```

### Steps to Reproduce
1. Add the latest alpha build from the ImageSharp nuget stream to an Android project.
2. In the Project Settings -> Android Options -> Linking, set it to "SDK Assemblies Only"
3. Try to build the project, and observe the linker error.

I have a sample project demonstrating this problem at: 
https://github.com/dmanning23/MonogameScreenToolsExample

### System Configuration
This is in an Android 8.1 project.

- ImageSharp version: v1.0.0-alpha9-00194
- Other ImageSharp packages and versions: Does not occur in the beta build on nuget.org
- Environment (Operating system, version and so on):Android 8.1
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
Alpha?

**Comment by antonfirsov** [comment]
@dmanning23 those old versions are no longer supported in any way, and will never work after the recent changes in dotnet runtime.

Since we are still in development phase (haven't reached 1.0 yet), we can only help if you are using the newest beta or dev/myget version. If you are experiencing performance regressions, you should open an issue describing your performance problem with detailed explanation + benchmarks.

**Comment by dmanning23** [comment]
Yeah, that's the version currently available from the myget stream at:
https://www.myget.org/F/imagesharp/api/v3/index.json
I found that in the documentation somewhere, is there another myget stream?

**Comment by antonfirsov** [comment]
@dmanning23 check out the URL @JimBobSquarePants linked in his answer. The feed you linked is from the Mesozoic Era, everything has been published under `F/sixlabors` in the last 2 years.  I really hope none of our docs does reference it any longer.

**Comment by dmanning23** [comment]
dang yall, how did I end up so far out in the weeds? I'll pull down the "good stuff" and try again :)

Cheers!

**Comment by JimBobSquarePants** [comment]
Haha... Fingers crossed it all works for you now. Any issues hit us up! 😄
