### ISSUE TITLE
Image.Load throws NullReferenceException

### ISSUE THREAD

**Issue by Metalnem** [SixLabors/ImageSharp#823]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

**Image.Load** throws **NullReferenceException** when loading malformed JPG file.

### Steps to Reproduce

Run the following code snippet with the ```path``` variable containing the path to the file from the [attached archive](https://github.com/SixLabors/ImageSharp/files/2802419/NullReferenceException.zip):

```csharp
Image.Load(path);
````

You will get the following stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SixLabors.ImageSharp.Formats.Jpeg.Components.Decoder.JpegFrame.Dispose()
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Dispose()
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Byte[] data)
```

### System Configuration

- ImageSharp version: Beta 6
- Environment (Operating system, version and so on): Windows 10 Pro 1803
- .NET Framework version: .NET Core 2.2.102

Found via [SharpFuzz](https://github.com/Metalnem/sharpfuzz).

**Comment by dlemstra** [comment]
Could you remove the numbering?
