### ISSUE TITLE
'Unable to cast object of type 'System.UInt32[]' to type 'System.UInt32'

### ISSUE THREAD

**Issue by 63Digital** [SixLabors/ImageSharp#936]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Attempting to load the attached image throws:
 `'System.InvalidCastException: 'Unable to cast object of type 'System.UInt32[]' to type 'System.UInt32'.'`

`   at SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifReader.GetThumbnail(UInt32 offset)
   at SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifReader.ReadValues()
   at SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile.InitializeValues()
   at SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile.TryGetValue(ExifTag tag, ExifValue& value)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.GetExifResolutionValue(ExifTag tag)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.InitDerivedMetadataProperties()
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func2 action)
   at SixLabors.ImageSharp.Image.Load(Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Configuration config, String path, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(String path)
 `

From having a look through the previous issues this might be EXIF related?

### Steps to Reproduce

Execute the code below on the attached sample image
`Image tmpImage = Image.Load(@"D:\test\path\image.jpg");`
          

### System Configuration

- ImageSharp version: 1.0.0-dev002724
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10, Visual Studio 2019 Preview 2
- .NET Framework version: Core 2.2
- Additional information:

Sample image

[testimage.zip](https://github.com/SixLabors/ImageSharp/files/3296756/testimage.zip)

**Comment by JimBobSquarePants** [comment]
I'll leave this one for you @dlemstra as it's probably affecting you Magick libraries also.

**Comment by JimBobSquarePants** [comment]
Fixed by #1067
