### ISSUE TITLE
Support for Net Core 3.0

### ISSUE THREAD

**Issue by prince272** [SixLabors/ImageSharp#985]
Is the ImageSharp supported for Net Core 3.0. There is an error when I try this           
  using (var image = Image.Load(bytes))
            {
                width = image.Width;
                height = image.Height;
            }

The error is:

System.NotSupportedException: Image cannot be loaded. Available decoders:
 - BMP : BmpDecoder
 - GIF : GifDecoder
 - PNG : PngDecoder
 - JPEG : JpegDecoder
 
 at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
 at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream)
 at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream)
 at SixLabors.ImageSharp.Image.Load(Stream stream)
 at

**Comment by prince272** [comment]
My problem have been solved. Saving the image to a file before reading the same stream caused that error. Thanks for you time. You can now close the comment.
